import { buildHistoricalUnits, type HistoricalLessonSeed, type HistoricalUnitSeed } from "../historical/buildHistoricalUnits";
const L=(title:string,reference:HistoricalLessonSeed["reference"],concept:[string,string],teaching:string,formation:string,question:HistoricalLessonSeed["question"],fill:HistoricalLessonSeed["fill"]):HistoricalLessonSeed=>({title,reference,concept,teaching,formation,question,fill});
const seeds:HistoricalUnitSeed[]=[
{id:"ruth-u01",title:"Lealdade no tempo da fome",subtitle:"Perda, retorno e provisão em Rute 1–2",chapters:[1,2],lessons:[
L("Fome e perda",["Rute 1:1–5",1,1,1,5],["ruth-loss","Luto em terra estrangeira"],"Nos dias dos juízes, uma família de Belém migra para Moabe por causa da fome. Noemi perde marido e filhos, ficando com as noras em profunda vulnerabilidade.","A Bíblia dá nome à dor sem oferecer explicações fáceis; lamento honesto faz parte da fé.",["De que cidade saiu a família de Elimeleque?","Belém","Jericó","Siló","Gibeá","Rute 1 identifica Belém de Judá como origem da família."],["A família foi a Moabe por causa da","fome",".","guerra de Saul","coroação","construção do templo","A crise alimentar inicia a migração."]),
L("Onde fores, irei",["Rute 1:6–18",1,6,1,18],["ruth-loyalty","Lealdade de Rute"],"Noemi decide voltar. Orfa se despede, mas Rute se apega à sogra e assume povo, caminho e Deus de Noemi, sem garantia de segurança.","Hesed, amor leal, aparece em compromisso concreto com uma pessoa vulnerável e atravessa barreiras nacionais.",["Quem permaneceu com Noemi?","Rute","Orfa","Boaz","Mara","Rute se apega a Noemi e acompanha seu retorno."],["O teu povo será o meu povo, e o teu Deus será o meu","Deus",".","rei","campo","juiz","Rute 1:16 expressa seu compromisso integral."]),
L("Noemi volta vazia",["Rute 1:19–22",1,19,1,22],["ruth-lament","Lamento, amargura e esperança discreta"],"Belém se comove com a chegada. Noemi pede ser chamada Mara, pois se percebe vazia, mas o narrador informa que chegam no início da colheita da cevada.","A comunidade não precisa corrigir imediatamente quem sofre; pode acolher o lamento e perceber sinais de esperança ainda invisíveis.",["Que nome Noemi pede que usem?","Mara","Hadassa","Débora","Abigail","Mara comunica a amargura que ela experimenta."],["Elas chegaram no começo da colheita da","cevada",".","uva","azeitona","figueira","O detalhe prepara a provisão do capítulo seguinte."]),
L("Rute respiga no campo",["Rute 2",2,1,2,23],["ruth-gleaning","Providência por meio de generosidade"],"Rute recolhe espigas deixadas para pobres e estrangeiros e chega ao campo de Boaz. Ele conhece sua lealdade, garante proteção e amplia a provisão.","A providência opera por leis justas, trabalho corajoso e generosidade que vai além do mínimo.",["Em cujo campo Rute respigou?","Boaz","Elimeleque","Quiliom","Samuel","Rute 2 apresenta Boaz como parente de Elimeleque."],["Boaz ordenou que Rute fosse tratada com","proteção",".","suspeita","violência","indiferença","Ele proíbe importunação e garante água e alimento."])
]},
{id:"ruth-u02",title:"Resgate e futuro",subtitle:"Iniciativa, justiça e restauração em Rute 3–4",chapters:[3,4],lessons:[
L("Noemi busca descanso",["Rute 3:1–5",3,1,3,5],["ruth-plan","Cuidado, risco e busca de futuro"],"Noemi deseja segurança para Rute e orienta uma aproximação a Boaz na eira. O plano nasce dentro dos costumes de parentesco, mas envolve risco social para ambas.","Buscar o bem de outra pessoa exige prudência; o texto deve ser lido em seu contexto cultural, sem transformar detalhes em fórmula romântica.",["O que Noemi desejava encontrar para Rute?","Descanso e segurança","Um exército","Um cargo sacerdotal","Uma viagem ao Egito","Rute 3:1 explicita a busca de bem-estar para a nora."],["O plano acontece na","eira",".","sinagoga","corte real","arca","Boaz estava peneirando cevada."]),
L("Estende a tua capa",["Rute 3:6–18",3,6,3,18],["ruth-redeemer-request","Pedido de resgate e integridade"],"Rute pede que Boaz estenda sua capa porque é resgatador. Ele reconhece sua bondade, protege sua reputação e explica que existe parente mais próximo.","Rute não é passiva: ela formula o pedido. Boaz responde com integridade, limites e compromisso público.",["Por que Boaz não resolve tudo imediatamente?","Havia um resgatador mais próximo","Não conhecia Rute","Era estrangeiro","A colheita terminou","A ordem de parentesco precisava ser respeitada."],["Rute pediu que Boaz agisse como","resgatador",".","juiz militar","profeta","rei","A imagem da capa comunica proteção e compromisso."]),
L("A decisão no portão",["Rute 4:1–12",4,1,4,12],["ruth-gate","Justiça pública e responsabilidade"],"Boaz reúne anciãos no portão e apresenta a questão ao parente mais próximo. A decisão ocorre diante de testemunhas, e Boaz assume resgate e casamento.","Boas intenções ganham forma por processos transparentes que protegem direitos e memória familiar.",["Onde a questão foi resolvida?","No portão da cidade","Na eira em segredo","Em Moabe","No palácio","O portão era espaço público de decisão e testemunho."],["Boaz agiu diante de","testemunhas",".","soldados","espias","mercadores egípcios","Os anciãos confirmam publicamente o acordo."]),
L("De vazio a plenitude",["Rute 4:13–22",4,13,4,22],["ruth-restoration","Restauração, comunidade e linhagem"],"Rute dá à luz Obede. As mulheres celebram com Noemi, e a genealogia liga o menino a Davi. Uma estrangeira fiel ocupa lugar central na história de Israel.","A restauração não apaga as perdas, mas cria futuro por meio de lealdade, comunidade e graça inclusiva.",["Quem foi o filho de Rute e Boaz?","Obede","Jessé","Davi","Elimeleque","Obede seria pai de Jessé e avô de Davi."],["A genealogia termina com","Davi",".","Moisés","Saul","Salomão","O livro conecta a história familiar ao futuro rei."])
]}
];
export const ruthUnits=buildHistoricalUnits("ruth","Rute",seeds);
