import {appendFileSync} from "node:fs";
const base=(process.env.NOAH_URL??"").replace(/\/$/,"");if(!base)throw new Error("NOAH_URL ausente");
const cases=[
{id:"romans-9",question:"Explique Romanos 9 considerando o contexto histórico, literário e teológico.",mode:"deepen",context:{area:"bible",title:"Gênesis 15",reference:"Gênesis 15"},required:[["angúst"],["promess","fidelidade"],["isaque"],["jacó"],["faraó"],["oleiro","barro"],["gentios"],["romanos 10"],["romanos 11"],["calvin","reformad"],["wesley","armini"]]},
{id:"agape",question:"Explique o significado de ἀγάπη no Novo Testamento.",mode:"ask",context:{area:"lexicon",title:"ἀγάπη",lexicalData:{lemma:"ἀγάπη",transliteration:"agapē",partOfSpeech:"substantivo feminino",strong:"G26",meanings:["amor","cuidado"],source:"TBESG / STEP Bible, CC BY 4.0"}},required:[["agápē","agape"],["substantiv"],["context"]]},
{id:"prevenient-grace",question:"Explique a graça preveniente na teologia wesleyana.",mode:"explain",context:{area:"formation",title:"Teologia wesleyana"},required:[["graça"],["wesley"],["resposta","responder"],["irresist"]]},
{id:"john-1",question:"Explique João 1:1 para alguém que começou a estudar a Bíblia.",mode:"simple",context:{area:"bible",title:"Introdução"},required:[["logos","verbo"],["prólogo","inicio","início"]]},
{id:"invalid-reference",question:"Explique o que Jesus disse em João 25:10.",mode:"ask",context:{area:"bible",title:"Introdução"},required:[["não existe"],["21 capítulo"]],critical:true},
{id:"different-context",question:"Explique a parábola do bom samaritano.",mode:"explain",context:{area:"bible",title:"Gênesis 15",reference:"Gênesis 15"},required:[["lucas 10"],["samaritano"]]},
{id:"short-answer",question:"Quem foi Timóteo?",mode:"ask",context:{area:"bible",title:"Introdução"},required:[["paulo"]],maxLength:1800},
{id:"divergence",question:"Romanos 9 prova a predestinação incondicional?",mode:"deepen",context:{area:"bible",title:"Romanos 9",reference:"Romanos 9"},required:[["calvin","reformad"],["wesley","armini"],["interpreta","leitura"]]},
{id:"wrong-quotation",question:"Em Romanos 9:24 Paulo compara Deus a um pai escolhendo seu filho?",mode:"ask",context:{area:"bible",title:"Romanos 9",reference:"Romanos 9:24"},required:[["não"],["judeus"],["gentios"]],critical:true},
{id:"insufficient-source",question:"Qual é a página exata do Manual da Igreja do Nazareno que explica a graça preveniente?",mode:"ask",context:{area:"formation",title:"Manual Nazareno"},required:[["edição","documento"],["não posso","não é possível","não tenho","limitação"]],forbidden:[/página\s+\d+/i],critical:true}
];
const norm=value=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const results=[];
for(const item of cases){const response=await fetch(base+"/v1/tutor",{method:"POST",headers:{Origin:"https://viniciusliniker1-spec.github.io","Content-Type":"application/json"},body:JSON.stringify({question:item.question,mode:item.mode,level:"intermediate",installationId:"github-theology-eval-v1",context:item.context})});const data=await response.json();if(!response.ok||!data.answer)throw new Error(item.id+": "+(data.message??data.error??response.status));const answer=norm(data.answer);const missing=item.required.filter(group=>!group.some(term=>answer.includes(norm(term)))).map(group=>group.join("|"));const forbidden=(item.forbidden??[]).filter(pattern=>pattern.test(data.answer)).map(String);const lengthOk=!item.maxLength||data.answer.length<=item.maxLength;const passed=missing.length===0&&forbidden.length===0&&lengthOk;results.push({id:item.id,passed,score:(item.required.length-missing.length)+"/"+item.required.length,missing,forbidden,length:data.answer.length,provider:data.provider,critical:Boolean(item.critical)});console.log(JSON.stringify(results.at(-1)))}
const criticalFailures=results.filter(item=>item.critical&&!item.passed);const passed=results.filter(item=>item.passed).length;const summary=["### Avaliação de conteúdo do Noah","","- Cenários: "+results.length,"- Heurísticas atendidas integralmente: "+passed+"/"+results.length,"- Falhas críticas: "+criticalFailures.length,"","| Cenário | Resultado | Cobertura |","|---|---:|---:|",...results.map(item=>"| "+item.id+" | "+(item.passed?"OK":item.critical?"FALHA CRÍTICA":"revisão editorial")+" | "+item.score+" |"),"","Heurísticas automáticas não equivalem a validação teológica humana."].join("\n");if(process.env.GITHUB_STEP_SUMMARY)appendFileSync(process.env.GITHUB_STEP_SUMMARY,summary+"\n");if(criticalFailures.length)process.exitCode=1;
