import { buildHistoricalUnits, type HistoricalLessonSeed, type HistoricalUnitSeed } from "../historical/buildHistoricalUnits";
const L=(title:string,reference:HistoricalLessonSeed["reference"],concept:[string,string],teaching:string,formation:string,question:HistoricalLessonSeed["question"],fill:HistoricalLessonSeed["fill"]):HistoricalLessonSeed=>({title,reference,concept,teaching,formation,question,fill});
const seeds: HistoricalUnitSeed[]=[
{id:"judges-u01",title:"O ciclo começa",subtitle:"Incompletude, aliança e primeiros libertadores em Juízes 1–3",chapters:[1,2,3],lessons:[
L("Uma conquista incompleta",["Juízes 1",1,1,1,36],["judges-incomplete","Obediência incompleta e convivência tensa"],"Depois da morte de Josué, as tribos continuam ocupando a terra, mas várias não expulsam os habitantes. O capítulo alterna avanços e fracassos e prepara o conflito espiritual do livro.","Pequenas acomodações repetidas podem formar padrões que afastam uma comunidade de sua vocação.",["Que tribo sobe primeiro contra os cananeus?","Judá","Benjamim","Dã","Levi","Juízes 1:2 indica Judá, acompanhado por Simeão."],["A narrativa registra uma ocupação","incompleta",".","instantânea","sem conflito","liderada por reis","O refrão sobre não expulsar povos prepara os ciclos seguintes."]),
L("O padrão de Juízes",["Juízes 2",2,1,2,23],["judges-cycle","Ciclo de infidelidade, opressão e libertação"],"Uma geração surge sem conhecer vivencialmente as obras do SENHOR. Israel abandona a aliança, sofre opressão, clama, recebe juízes e volta a se desviar após a morte deles.","O livro descreve uma espiral, não um modelo heroico. A misericórdia de Deus encontra um povo instável, mas o pecado produz dano crescente.",["O que Deus levantava quando o povo era oprimido?","Juízes","Faraós","Sacerdotes egípcios","Imperadores","Juízes 2 resume a ação libertadora por meio dos juízes."],["Depois da morte de cada juiz, o povo voltava a se","corromper",".","organizar","mudar de terra","tornar sacerdote","A recaída repetida estrutura o livro."]),
L("Otniel e Eúde",["Juízes 3:1–30",3,1,3,30],["judges-first-deliverers","Primeiros libertadores e misericórdia"],"Otniel é levantado quando Israel clama. Depois, Eúde usa sua condição de canhoto e uma estratégia arriscada contra Eglom, libertando o povo de Moabe.","Deus age por pessoas inesperadas, mas a violência da narrativa pertence ao conflito nacional antigo e não é método para a missão cristã.",["Qual característica de Eúde é destacada?","Era canhoto","Era sacerdote","Era gigante","Era rei de Judá","Juízes 3:15 identifica Eúde como homem canhoto."],["Quando Israel clamou, Deus levantou um","libertador",".","faraó","ídolo","mercador","O clamor e a libertação reaparecem nos ciclos."]),
L("Sangar e o aguilhão",["Juízes 3:31",3,31],["judges-shamgar","Serviço com recursos disponíveis"],"Sangar recebe apenas um versículo: ele fere filisteus com um aguilhão de bois e também liberta Israel. A brevidade mostra que nem todo serviço fiel recebe longa narrativa.","Importância diante de Deus não depende do espaço ocupado em registros humanos.",["Que instrumento Sangar usou?","Um aguilhão de bois","Uma funda","Uma trombeta","Uma espada de Golias","Juízes 3:31 preserva esse detalhe incomum."],["Sangar também libertou a","Israel",".","Moabe","Filístia","Síria","O breve relato o inclui entre os libertadores."])
]},
{id:"judges-u02",title:"Débora e Gideão",subtitle:"Profecia, coragem e fragilidade em Juízes 4–8",chapters:[4,5,6,7,8],lessons:[
L("Débora, Baraque e Jael",["Juízes 4",4,1,4,24],["judges-deborah","Liderança feminina e libertação"],"Débora julga Israel e transmite a ordem divina a Baraque. Jael derrota Sísera, e a vitória envolve mulheres exercendo liderança, discernimento e coragem.","O texto confronta expectativas estreitas sobre quem pode servir como agente na história de Deus.",["Quem julgava Israel debaixo de uma palmeira?","Débora","Jael","Miriã","Noemi","Juízes 4 apresenta Débora como profetisa e juíza."],["A vitória sobre Sísera veio pela mão de uma","mulher",".","criança","cidade","estátua","Débora antecipa que a honra final seria dada a uma mulher."]),
L("O cântico de Débora",["Juízes 5",5,1,5,31],["judges-song","Memória poética e participação"],"Débora e Baraque cantam a vitória, elogiam tribos que se ofereceram e questionam as que permaneceram distantes. A poesia interpreta a batalha como ação de Deus e resposta comunitária.","Celebrar também é examinar participação: quem se apresentou para servir e quem preferiu segurança?",["Quem cantou após a vitória?","Débora e Baraque","Gideão e Sansão","Eúde e Otniel","Noemi e Rute","Juízes 5:1 nomeia os cantores."],["O cântico louva os que se ofereceram","voluntariamente",".","por pagamento","em segredo","contra Israel","A disponibilidade do povo é motivo de bênção."]),
L("O chamado de Gideão",["Juízes 6",6,1,6,40],["judges-gideon-call","Chamado em meio ao medo"],"Gideão malha trigo escondido quando é chamado de homem valente. Ele derruba o altar de Baal, pede sinais e aprende que a presença de Deus é maior que sua sensação de insuficiência.","Deus encontra pessoas amedrontadas sem romantizar o medo e as conduz em passos de obediência.",["Onde Gideão malhava o trigo?","No lagar","No templo","No palácio","À margem do Jordão","Ele se escondia dos midianitas no lagar."],["O altar que Gideão derrubou era dedicado a","Baal",".","Moisés","Josué","Davi","A primeira ação confronta idolatria dentro de sua casa."]),
L("Trezentos e um final ambíguo",["Juízes 7–8",7,1,8,35],["judges-gideon-ambiguity","Vitória sem vanglória e risco do poder"],"O exército é reduzido a trezentos para que Israel não se glorie. Gideão vence, recusa o título de rei, mas depois produz um éfode que se torna laço e vive com privilégios reais.","Uma boa vitória não torna todas as escolhas posteriores corretas; líderes também precisam de prestação de contas.",["Por que o exército foi reduzido?","Para Israel não se gloriar","Porque faltou alimento","Para fugir de Canaã","Porque Gideão desistiu","Juízes 7:2 explica que a redução impede vanglória."],["O éfode de Gideão tornou-se um","laço",".","mapa","instrumento agrícola","selo real","Juízes 8 termina com ambiguidade sobre seu legado."])
]},
{id:"judges-u03",title:"Ambição e libertação",subtitle:"Abimeleque, Jefté e juízes menores em Juízes 9–12",chapters:[9,10,11,12],lessons:[
L("Abimeleque toma o poder",["Juízes 9",9,1,9,57],["judges-abimelech","Ambição, violência e falsa realeza"],"Abimeleque mata seus irmãos e compra apoio para reinar. A parábola de Jotão compara sua liderança ao espinheiro; a violência que o elevou volta contra ele.","Poder obtido por medo e eliminação de rivais carrega sementes de autodestruição.",["Na parábola de Jotão, qual planta aceita governar?","O espinheiro","A oliveira","A figueira","A videira","As árvores produtivas recusam abandonar seu fruto; o espinheiro aceita."],["Abimeleque chegou ao poder por meio da","violência",".","herança davídica","profecia de Samuel","escolha de Josué","O massacre dos irmãos fundamenta seu governo."]),
L("Deuses que não salvam",["Juízes 10",10,1,10,18],["judges-false-gods","Arrependimento além das palavras"],"Após Tola e Jair, Israel volta à idolatria. Quando clama, Deus expõe a inutilidade dos deuses escolhidos; o povo remove os ídolos e serve ao SENHOR.","Arrependimento bíblico não é apenas pedido de socorro, mas abandono concreto das lealdades concorrentes.",["O que o povo fez além de confessar?","Removeu os deuses estrangeiros","Construiu um palácio","Escolheu um faraó","Abandonou a terra","Juízes 10:16 liga remoção de ídolos e serviço ao SENHOR."],["Arrependimento envolve mudança de","lealdade",".","clima","idioma","fronteira","O povo deixa os ídolos e volta a servir."]),
L("O voto de Jefté",["Juízes 11",11,1,11,40],["judges-jephthah-vow","Votos precipitados e tragédia"],"Jefté é rejeitado, chamado de volta e usado na libertação. Contudo faz um voto precipitado que envolve sua filha e transforma vitória em tragédia.","O narrador não manda imitar o voto. Zelo sem conhecimento e palavras imprudentes podem ferir quem deveria ser protegido.",["Quem saiu primeiro para encontrar Jefté?","Sua filha","O rei amonita","Gideão","Um sacerdote","Juízes 11 apresenta a filha única recebendo o vencedor."],["O voto precipitado transformou vitória em","tragédia",".","coroação","aliança","colheita","O episódio adverte contra religiosidade irresponsável."]),
L("A palavra que denuncia",["Juízes 12",12,1,12,15],["judges-shibboleth","Conflito interno e identidade"],"Efraim entra em conflito com Jefté. A pronúncia de uma palavra, chibolete, identifica fugitivos e a guerra interna mata milhares; depois vêm três juízes menores.","A espiral agora volta a violência contra irmãos. Diferenças de identidade viram instrumentos de exclusão e morte.",["Que palavra era usada no teste de pronúncia?","Chibolete","Ebenézer","Hosana","Maranata","Juízes 12 registra o teste linguístico."],["A violência passou a atingir tribos de","Israel",".","Egito","Babilônia","Pérsia","O conflito interno revela agravamento da desordem."])
]},
{id:"judges-u04",title:"Sansão",subtitle:"Dom, vocação e autodestruição em Juízes 13–16",chapters:[13,14,15,16],lessons:[
L("Um nascimento anunciado",["Juízes 13",13,1,13,25],["judges-samson-call","Vocação recebida antes do nascimento"],"Um mensageiro anuncia à mulher de Manoá que seu filho será nazireu e começará a libertar Israel. A mãe sem nome recebe e segue instruções centrais.","O chamado é dom da graça antes de ser conquista pessoal; vocação exige cuidado e formação.",["Qual voto marcaria Sansão?","Nazireado","Voto de rei","Sacerdócio levítico","Peregrinação anual","Juízes 13 associa sua vida ao nazireado desde o ventre."],["Sansão começaria a libertar Israel dos","filisteus",".","moabitas","egípcios","babilônios","O anúncio define o horizonte de sua missão."]),
L("Força sem domínio próprio",["Juízes 14",14,1,14,20],["judges-samson-desire","Desejo impulsivo e vocação"],"Sansão insiste em casar com uma filisteia, toca o cadáver do leão e transforma a festa em disputa por enigma. Seu dom opera, mas seus desejos desordenados produzem conflito.","Capacidade extraordinária não substitui caráter; dons sem domínio próprio podem ferir o próprio chamado.",["O que Sansão encontrou no cadáver do leão?","Mel","Uma espada","Água","Um rolo","O mel fornece a imagem de seu enigma."],["O enigma de Sansão alimentou um","conflito",".","culto","tratado de paz","casamento de Rute","A disputa termina em ameaça, violência e ruptura."]),
L("Vingança em espiral",["Juízes 15",15,1,15,20],["judges-samson-revenge","Ciclo pessoal de vingança"],"Sansão, os filisteus e homens de Judá reagem uns aos outros com retaliações crescentes. Deus ainda usa Sansão para livrar, mas a narrativa mostra uma espiral destrutiva.","Ser usado por Deus não transforma toda motivação pessoal em santa. Vingança e missão não são sinônimos.",["Que objeto Sansão usou contra mil homens?","Uma queixada de jumento","Uma funda","Uma lança real","Uma trombeta","Juízes 15:15 destaca a queixada fresca."],["A retaliação gerou nova","retaliação",".","aliança","colheita","profecia","Cada ato chama outro ato de violência."]),
L("Dalila e a queda",["Juízes 16",16,1,16,31],["judges-samson-fall","Segredo, queda e misericórdia final"],"Dalila pressiona Sansão até ele revelar o sinal de seu nazireado. Cego e humilhado, ele reconhece dependência de Deus e pede força uma última vez.","O final é trágico: graça ainda encontra Sansão, mas não apaga as consequências de escolhas repetidas.",["Onde estava o sinal do nazireado de Sansão?","Em seu cabelo não cortado","Em um anel","Em sua sandália","Em uma coroa","Sansão revela que navalha nunca passara por sua cabeça."],["No fim, Sansão voltou a depender de","Deus",".","Dalila","sua fama","Judá","Sua oração reconhece que força não era propriedade autônoma."])
]},
{id:"judges-u05",title:"Quando cada um faz o que quer",subtitle:"Idolatria e colapso social em Juízes 17–21",chapters:[17,18,19,20,21],lessons:[
L("Mica e seu santuário",["Juízes 17",17,1,17,13],["judges-micah-idols","Religião moldada ao interesse próprio"],"Mica cria ídolos, um éfode e seu próprio sacerdócio, depois contrata um levita acreditando garantir prosperidade. Linguagem religiosa encobre culto feito sob medida.","Proximidade de símbolos bíblicos não corrige uma espiritualidade centrada em controle e vantagem.",["Por que Mica ficou confiante ao contratar o levita?","Achou que o SENHOR o faria prosperar","Recebeu ordem de Débora","Foi coroado rei","A arca chegou à casa","Juízes 17:13 expõe sua lógica utilitária."],["Mica tentou usar a religião para garantir","prosperidade",".","arrependimento","justiça","reconciliação","O santuário doméstico serve ao projeto pessoal."]),
L("Dã toma Laís",["Juízes 18",18,1,18,31],["judges-dan-laish","Migração, violência e idolatria"],"A tribo de Dã procura território, rouba os objetos de Mica, leva o levita e destrói Laís, uma cidade desprevenida. Depois instala a imagem esculpida.","O capítulo retrata sucesso aparente sem aprovação moral: expansão, culto e liderança podem se corromper juntos.",["Que cidade os danitas conquistaram e renomearam?","Laís","Belém","Jericó","Hebrom","Juízes 18 descreve Laís, depois chamada Dã."],["Os danitas levaram ídolos e também o","levita",".","rei","profeta Samuel","juiz Otniel","O sacerdote escolhe uma posição maior, revelando ambição."]),
L("A violência em Gibeá",["Juízes 19",19,1,19,30],["judges-gibeah","Desumanização e ausência de hospitalidade"],"Uma mulher é brutalizada em Gibeá e sua morte convoca horror nacional. O texto não deve ser suavizado: mostra o abismo alcançado quando pessoas vulneráveis são tratadas como objetos.","A passagem exige lamento e compromisso com proteção, não curiosidade mórbida nem culpa da vítima.",["Em que território ocorreu o crime?","Benjamim","Judá","Moabe","Efraim oriental","Gibeá pertencia a Benjamim."],["O episódio revela profunda","desumanização",".","prosperidade","sabedoria real","unidade","A vulnerável é sacrificada em uma sociedade sem justiça."]),
L("Guerra civil e um final sombrio",["Juízes 20–21",20,1,21,25],["judges-civil-war","Caos moral e soluções violentas"],"Israel combate Benjamim, quase elimina a tribo e depois cria soluções violentas para preservá-la. O refrão final declara que cada um fazia o que parecia certo aos próprios olhos.","A ausência de rei é também ausência de governo justo sob Deus; o livro termina pedindo uma liderança diferente, sem afirmar que qualquer monarquia resolverá o coração humano.",["Qual refrão encerra o livro?","Cada um fazia o que parecia certo aos seus olhos","Israel nunca errou","Gideão reinou para sempre","A terra ficou sem conflitos","Juízes 21:25 resume a desordem moral."],["A guerra quase eliminou a tribo de","Benjamim",".","Levi","Judá","Issacar","A reação ao crime também se torna excessiva e destrutiva."])
]}
];
export const judgesUnits=buildHistoricalUnits("judges","Juízes",seeds);
