import { buildHistoricalUnits, type HistoricalLessonSeed, type HistoricalUnitSeed } from "../historical/buildHistoricalUnits";
const L=(title:string,reference:HistoricalLessonSeed["reference"],concept:[string,string],teaching:string,formation:string,question:HistoricalLessonSeed["question"],fill:HistoricalLessonSeed["fill"]):HistoricalLessonSeed=>({title,reference,concept,teaching,formation,question,fill});
const seeds:HistoricalUnitSeed[]=[
{id:"2-samuel-u01",title:"Davi se torna rei",subtitle:"Luto, conflito e unificação em 2 Samuel 1–5",chapters:[1,2,3,4,5],lessons:[
L("Davi lamenta Saul e Jônatas",["2 Samuel 1",1,1,1,27],["second-samuel-lament","Luto que honra a complexidade"],"Davi recebe notícia da morte de Saul, pune o mensageiro que alegou matá-lo e compõe um lamento por Saul e Jônatas. Ele não celebra a queda do perseguidor.","Lamento maduro reconhece valor e perda sem negar conflitos passados.",["Como Davi reagiu à morte de Saul?","Com lamento","Com uma festa","Com indiferença","Com coroação imediata","Ele rasga as vestes, jejua e ensina o cântico."],["Davi chama Jônatas de irmão muito","amado",".","temido","distante","rico","O lamento preserva a profundidade da amizade."]),
L("Duas casas em conflito",["2 Samuel 2",2,1,2,32],["second-samuel-divided","Reino dividido e custo da guerra"],"Davi é ungido rei de Judá em Hebrom, enquanto Isbosete é estabelecido sobre outras tribos. Uma disputa entre guerreiros inicia conflito que mata Asael.","Transições de poder podem transformar pessoas em peças; o texto mostra o custo humano da rivalidade política.",["Onde Davi foi ungido rei de Judá?","Hebrom","Jerusalém","Belém","Gilgal","2 Samuel 2 situa a primeira coroação em Hebrom."],["Abner comandava a casa de","Saul",".","Davi","Samuel","Eli","Ele estabelece Isbosete e lidera suas forças."]),
L("Abner e Isbosete",["2 Samuel 3–4",3,1,4,12],["second-samuel-abner","Intriga, assassinato e justiça"],"Abner rompe com Isbosete e negocia com Davi, mas Joabe o mata por vingança. Depois assassinos levam a cabeça de Isbosete esperando recompensa; Davi os condena.","Davi distancia sua ascensão de assassinato político e lamenta vidas tratadas como degraus para o poder.",["Quem matou Abner?","Joabe","Davi","Isbosete","Asael","Joabe o mata em Hebrom por causa de Asael."],["Davi condenou os assassinos de","Isbosete",".","Golias","Samuel","Aquis","Ele não aceitou violência oportunista como lealdade."]),
L("Rei de todo Israel",["2 Samuel 5",5,1,5,25],["second-samuel-united","Unificação, Jerusalém e dependência"],"As tribos reconhecem Davi como pastor e governante. Ele toma Jerusalém e consulta a Deus antes de enfrentar os filisteus em duas batalhas com orientações diferentes.","Experiência anterior não elimina a necessidade de nova direção; liderança une povo, lugar e dependência contínua.",["Que cidade Davi tomou como capital?","Jerusalém","Jericó","Siló","Ramá","A fortaleza de Sião torna-se cidade de Davi."],["Antes das batalhas, Davi","consultou a Deus",".","copiou Saul","pediu ajuda ao Egito","fugiu para Moabe","As respostas distintas exigem atenção, não fórmula."])
]},
{id:"2-samuel-u02",title:"Aliança e bondade",subtitle:"A arca, a promessa e Mefibosete em 2 Samuel 6–9",chapters:[6,7,8,9],lessons:[
L("A arca chega a Jerusalém",["2 Samuel 6",6,1,6,23],["second-samuel-ark","Alegria e reverência na adoração"],"A primeira tentativa de transportar a arca ignora as exigências e termina com a morte de Uzá. Depois Davi a conduz com sacrifício e dança diante de Deus.","Entusiasmo e reverência não são opostos; boa intenção precisa respeitar a santidade de Deus.",["Quem morreu ao tocar a arca?","Uzá","Obede-Edom","Mical","Natã","Uzá segura a arca quando os bois tropeçam."],["Davi dançou diante do SENHOR com","alegria",".","vergonha","silêncio","armadura","A segunda procissão combina celebração e sacrifício."]),
L("Deus promete uma casa",["2 Samuel 7",7,1,7,29],["second-samuel-covenant","Aliança davídica e graça"],"Davi deseja construir uma casa para Deus, mas Deus relembra que foi ele quem tomou Davi do pasto e promete estabelecer sua casa e reino.","A promessa começa na iniciativa divina. O Novo Testamento relaciona sua esperança ao Messias, sem confundir cada rei davídico com governo perfeito.",["Quem apresentou a palavra de Deus a Davi?","Natã","Samuel","Gade","Zadoque","Natã primeiro aprova o plano, depois recebe correção divina."],["Deus prometeu edificar uma","casa para Davi",".","torre em Babel","pirâmide","arca nova","Casa aqui inclui dinastia e futuro."]),
L("Vitórias e justiça",["2 Samuel 8",8,1,8,18],["second-samuel-kingdom","Administração de justiça no reino"],"O capítulo resume vitórias, tributos e organização do governo. Seu centro declara que Davi administrava justiça e equidade a todo o povo.","Sucesso territorial precisa ser avaliado pelo exercício da justiça, não apenas por expansão e riqueza.",["O que Davi administrava a todo o povo?","Justiça e equidade","Trabalho forçado apenas","Culto a Dagom","Tributo egípcio","2 Samuel 8:15 resume a responsabilidade real."],["O reino deveria servir à","justiça",".","vaidade","vingança","idolatria","O resumo ético interpreta a administração."]),
L("Bondade a Mefibosete",["2 Samuel 9",9,1,9,13],["second-samuel-mephibosheth","Lealdade da aliança e mesa inclusiva"],"Davi procura alguém da casa de Saul para mostrar bondade por causa de Jônatas. Mefibosete recebe terras e passa a comer continuamente à mesa do rei.","Hesed transforma um possível rival vulnerável em hóspede honrado e cumpre uma promessa antiga.",["Por causa de quem Davi mostrou bondade a Mefibosete?","Jônatas","Abner","Joabe","Natã","A aliança com Jônatas orienta sua ação."],["Mefibosete passou a comer à mesa do","rei",".","sacerdote","filisteu","profeta","A mesa comunica pertencimento e dignidade."])
]},
{id:"2-samuel-u03",title:"Pecado no palácio",subtitle:"Guerra, abuso de poder e confronto em 2 Samuel 10–12",chapters:[10,11,12],lessons:[
L("Embaixadores humilhados",["2 Samuel 10",10,1,10,19],["second-samuel-ammon","Suspeita que produz guerra"],"Davi envia consolo ao novo rei amonita, mas conselheiros interpretam a missão como espionagem. A humilhação dos mensageiros desencadeia guerra.","Suspeita alimentada sem investigação pode transformar gesto de paz em conflito destrutivo.",["Por que Davi enviou servos a Hanum?","Para consolá-lo","Para coroá-lo","Para roubar a cidade","Para buscar a arca","Ele desejava retribuir bondade do pai de Hanum."],["Os conselheiros interpretaram o consolo como","espionagem",".","aliança","adoração","tributo","A leitura hostil inicia a crise."]),
L("Davi e Bate-Seba",["2 Samuel 11",11,1,11,27],["second-samuel-bathsheba","Abuso de poder e encobrimento"],"Davi permanece em Jerusalém, toma Bate-Seba e tenta encobrir a gravidez. Quando Urias age com lealdade, o rei organiza sua morte em combate.","O texto expõe abuso do poder real: Davi toma, manipula e mata. Bate-Seba não deve ser culpada pelas decisões do rei.",["Quem levou a carta com sua própria sentença?","Urias","Joabe","Natã","Absalão","Davi entrega a Urias instruções para colocá-lo na linha de morte."],["O que Davi fez desagradou ao","SENHOR",".","Egito","povo filisteu","rei de Moabe","O narrador oferece avaliação moral inequívoca."]),
L("Tu és o homem",["2 Samuel 12:1–15",12,1,12,15],["second-samuel-nathan","Confronto profético e arrependimento"],"Natã conta a parábola da cordeira tomada pelo rico. Davi condena o agressor e ouve: tu és o homem. Ele confessa seu pecado, mas consequências permanecem.","Arrependimento começa quando a pessoa deixa de manipular a narrativa e assume responsabilidade.",["Quem confrontou Davi?","Natã","Joabe","Zadoque","Mefibosete","O profeta usa uma parábola para revelar o abuso."],["A frase central do confronto foi: Tu és o","homem",".","rei perfeito","profeta","estrangeiro","Natã aplica a história diretamente a Davi."]),
L("Perda e novo começo",["2 Samuel 12:16–31",12,16,12,31],["second-samuel-solomon","Luto, consolo e continuidade"],"Davi jejua enquanto a criança vive, depois se levanta quando ela morre. Bate-Seba dá à luz Salomão, também chamado Jedidias, amado do SENHOR.","A graça abre futuro sem chamar o mal de bem nem apagar o luto e suas consequências.",["Que filho nasceu depois e foi amado pelo SENHOR?","Salomão","Amnom","Absalão","Adonias","Natã lhe dá também o nome Jedidias."],["O novo nascimento não apagou o","luto",".","reino","templo","exército","Restauração e dor coexistem na narrativa."])
]},
{id:"2-samuel-u04",title:"A casa dividida",subtitle:"Violência familiar e rebelião em 2 Samuel 13–16",chapters:[13,14,15,16],lessons:[
L("Tamar silenciada",["2 Samuel 13",13,1,13,39],["second-samuel-tamar","Violência sexual e omissão"],"Amnom arma uma situação para violentar Tamar e depois a rejeita. Ela protesta com clareza; Davi se ira, mas não promove justiça, e Absalão planeja vingança.","O texto exige ouvir a vítima, nomear a violência e reconhecer o dano produzido por abuso e omissão.",["Quem advertiu Amnom de que seu ato seria loucura?","Tamar","Jonadabe","Davi","Absalão","Tamar fala com lucidez antes e depois da violência."],["A omissão de Davi deixou a injustiça sem","resposta",".","testemunha","vítima","segredo","A falta de justiça alimenta a vingança de Absalão."]),
L("Absalão retorna",["2 Samuel 14",14,1,14,33],["second-samuel-absalom-return","Reconciliação incompleta"],"Joabe usa uma mulher sábia para convencer Davi a permitir o retorno de Absalão. Porém pai e filho ficam anos sem encontro; o retorno político não restaura a relação.","Reconciliação superficial, sem verdade e responsabilidade, pode deixar o conflito amadurecendo em silêncio.",["Quem organizou a fala da mulher sábia?","Joabe","Natã","Zadoque","Mefibosete","Joabe conduz a estratégia para trazer Absalão."],["Absalão voltou, mas a relação não foi plenamente","restaurada",".","registrada","esquecida","celebrada","A distância entre pai e filho continuou."]),
L("Absalão rouba corações",["2 Samuel 15",15,1,15,37],["second-samuel-rebellion","Populismo e rebelião"],"Absalão se posiciona junto ao caminho, promete justiça e conquista a lealdade popular. Proclama-se rei em Hebrom, e Davi foge de Jerusalém.","Aparência de acesso e promessas fáceis podem servir a um projeto de poder que explora frustrações reais.",["Onde Absalão foi proclamado rei?","Hebrom","Jerusalém","Belém","Ramá","Ele usa Hebrom como início da conspiração."],["Absalão furtava o coração do povo de","Israel",".","Moabe","Egito","Filístia","O texto descreve construção calculada de popularidade."]),
L("Humilhação no caminho",["2 Samuel 16",16,1,16,23],["second-samuel-flight","Crise, acusações e discernimento"],"Na fuga, Ziba acusa Mefibosete e recebe seus bens; Simei amaldiçoa Davi, que recusa matá-lo. Em Jerusalém, o conselho de Aitofel fortalece a ruptura pública.","Crises exigem cautela: informações podem ser interessadas, e suportar insulto pode ser mais sábio que reagir com violência.",["Quem amaldiçoou Davi durante a fuga?","Simei","Ziba","Husai","Aitofel","Simei lança pedras e acusa o rei."],["Davi impediu que Simei fosse","morto",".","ouvido","perdoado","exilado","Ele admite que a humilhação pode estar sob permissão divina."])
]},
{id:"2-samuel-u05",title:"A rebelião termina",subtitle:"Conselhos, batalha e luto em 2 Samuel 17–20",chapters:[17,18,19,20],lessons:[
L("Conselhos em disputa",["2 Samuel 17",17,1,17,29],["second-samuel-counsel","Sabedoria, estratégia e providência"],"Aitofel propõe ataque rápido, mas Husai recomenda demora e envia aviso a Davi. O conselho de Aitofel é frustrado, dando tempo aos fugitivos.","Planejamento importa, mas a narrativa também reconhece providência operando por redes humanas corajosas.",["De quem era o conselho que Absalão aceitou?","Husai","Aitofel","Joabe","Simei","A demora sugerida por Husai favorece Davi."],["Mensageiros avisaram Davi para atravessar o","Jordão",".","Nilo","Mar Vermelho","Quisom","A informação permitiu retirada segura."]),
L("Absalão morre",["2 Samuel 18",18,1,18,33],["second-samuel-absalom-death","Vitória pública e dor pessoal"],"Davi ordena que tratem Absalão com brandura, mas Joabe o mata quando fica preso na árvore. A vitória do reino se torna lamento de um pai.","Resultados políticos não eliminam vínculos e sofrimento; Davi chora o filho que tentou destroná-lo.",["Quem matou Absalão?","Joabe","Davi","Husai","Aitofel","Joabe desobedece à ordem de poupar o jovem."],["Ao receber a notícia, Davi","chorou",".","dançou","abdicou","atacou Joabe","Seu lamento domina o final do capítulo."]),
L("O rei retorna",["2 Samuel 19",19,1,19,43],["second-samuel-return","Retorno, perdão e tensões"],"Joabe confronta Davi por desmoralizar os soldados. O rei retorna, perdoa Simei, revê Mefibosete e honra Barzilai, mas tensões entre Judá e Israel persistem.","Restauração pública envolve gratidão e decisões difíceis; reconciliação apressada pode não resolver versões conflitantes.",["Quem recusou acompanhar Davi por causa da idade?","Barzilai","Simei","Ziba","Joabe","Barzilai havia sustentado o rei e pede para ficar."],["O retorno não eliminou as tensões entre Judá e","Israel",".","Egito","Moabe","Edom","A disputa prepara nova rebelião."]),
L("Seba e a mulher sábia",["2 Samuel 20",20,1,20,26],["second-samuel-sheba","Sabedoria que preserva uma cidade"],"Seba convoca Israel contra Davi. Joabe cerca Abel-Bete-Maaca, mas uma mulher sábia negocia e impede a destruição da cidade.", "A coragem de dialogar pode conter a lógica militar e proteger muitos inocentes.",["Quem negociou com Joabe?","Uma mulher sábia","Davi","Bate-Seba","Natã","A mulher fala em nome da cidade sitiada."],["A negociação preservou a","cidade",".","rebelião","coroa de Saul","arca filisteia","A comunidade entrega Seba e evita destruição."])
]},
{id:"2-samuel-u06",title:"Justiça, cântico e legado",subtitle:"Memória final do reinado em 2 Samuel 21–24",chapters:[21,22,23,24],lessons:[
L("Uma fome e uma dívida antiga",["2 Samuel 21:1–14",21,1,21,14],["second-samuel-gibeonites","Responsabilidade histórica e lamento"],"A fome é relacionada ao ataque de Saul aos gibeonitas, que violou antiga aliança. A solução é severa, e Rispa vigia os corpos até Davi providenciar sepultamento digno.","O texto une responsabilidade coletiva e protesto silencioso de uma mãe; sua violência não deve ser reproduzida como mecanismo de justiça atual.",["Quem protegeu os corpos expostos?","Rispa","Mical","Tamar","Abigail","Rispa mantém vigília até que Davi responda."],["A crise lembrava uma aliança com os","gibeonitas",".","filisteus","egípcios","moabitas","A palavra quebrada por Saul tinha consequência pública."]),
L("O cântico de libertação",["2 Samuel 21:15–22:51",21,15,22,51],["second-samuel-song","Deus como rocha e libertador"],"Após relatos de guerreiros, Davi canta que Deus é rocha, fortaleza e libertador. A poesia relembra perigos e atribui a salvação à ação divina.","Testemunho transforma sobrevivência em gratidão, sem negar que a vida de Davi também exige arrependimento.",["Qual imagem Davi usa repetidamente para Deus?","Rocha","Pirâmide","Carruagem egípcia","Espinheiro","2 Samuel 22 celebra Deus como rocha e fortaleza."],["O cântico atribui libertação a","Deus",".","sorte","armadura de Saul","alianças filisteias","A memória é reorganizada como louvor."]),
L("Últimas palavras e valentes",["2 Samuel 23",23,1,23,39],["second-samuel-mighty","Liderança justa e serviço compartilhado"],"As últimas palavras de Davi comparam o governante justo à luz da manhã. A lista dos valentes mostra que o reino não foi construído por uma pessoa sozinha; inclui também Urias, lembrando a ferida moral.","Liderança depende de muitos nomes e deve ser medida por justiça e temor de Deus, não por culto ao herói.",["A que é comparado o governante justo?","À luz da manhã","À noite sem estrelas","Ao deserto seco","Ao muro de Jericó","2 Samuel 23 usa imagens de amanhecer e chuva."],["A lista termina incluindo","Urias",".","Faraó","Samuel","Golias","Seu nome impede uma memória conveniente do reinado."]),
L("O censo e a eira",["2 Samuel 24",24,1,24,25],["second-samuel-census","Orgulho, arrependimento e culto custoso"],"Davi ordena um censo militar apesar da advertência de Joabe, depois reconhece pecado. Na eira de Araúna, recusa oferecer a Deus algo que não lhe custe nada.","Contar recursos pode se tornar confiança orgulhosa; arrependimento assume responsabilidade e responde com entrega real.",["De quem Davi comprou a eira?","Araúna","Joabe","Natã","Absalão","A eira jebuseia torna-se lugar de altar."],["Davi recusou oferecer sacrifício que não lhe","custasse",".","agradasse","pertencesse a Saul","desse vitória","2 Samuel 24:24 associa culto e entrega responsável."])
]}
];
export const secondSamuelUnits=buildHistoricalUnits("2-samuel","2 Samuel",seeds);
