export interface BibleBook { osis:string; name:string; chapters:number; aliases:string[] }
export interface BibleReference { book:BibleBook; chapter:number; verseStart?:number; verseEnd?:number; label:string; origin:"question"|"lesson"|"topic"|"answer" }
interface BibleVerse { number:number; text:string }
interface BibleChapter { chapter:number; verses:BibleVerse[] }
interface BibleBookData { book:string; chapters:BibleChapter[] }
const row=(osis:string,name:string,chapters:number,aliases:string[]):BibleBook=>({osis,name,chapters,aliases:[name,osis,...aliases]});
export const BIBLE_BOOKS:BibleBook[]=[
row("Gen","Gênesis",50,["Gn","Genesis"]),row("Exod","Êxodo",40,["Ex","Êx","Exodo"]),row("Lev","Levítico",27,["Lv","Levitico"]),row("Num","Números",36,["Nm","Numeros"]),row("Deut","Deuteronômio",34,["Dt","Deuteronomio"]),
row("Josh","Josué",24,["Js","Josue"]),row("Judg","Juízes",21,["Jz","Juizes"]),row("Ruth","Rute",4,["Rt"]),row("1Sam","1 Samuel",31,["1Sm","1 Sam"]),row("2Sam","2 Samuel",24,["2Sm","2 Sam"]),
row("1Kgs","1 Reis",22,["1Rs"]),row("2Kgs","2 Reis",25,["2Rs"]),row("1Chr","1 Crônicas",29,["1Cr","1 Cronicas"]),row("2Chr","2 Crônicas",36,["2Cr","2 Cronicas"]),row("Ezra","Esdras",10,["Ed"]),
row("Neh","Neemias",13,["Ne"]),row("Esth","Ester",10,["Et"]),row("Job","Jó",42,["Jó"]),row("Ps","Salmos",150,["Sl","Salmo"]),row("Prov","Provérbios",31,["Pv","Proverbios"]),
row("Eccl","Eclesiastes",12,["Ec"]),row("Song","Cânticos",8,["Ct","Cantares","Canticos"]),row("Isa","Isaías",66,["Is","Isaias"]),row("Jer","Jeremias",52,["Jr"]),row("Lam","Lamentações",5,["Lm","Lamentacoes"]),
row("Ezek","Ezequiel",48,["Ez"]),row("Dan","Daniel",12,["Dn"]),row("Hos","Oseias",14,["Os"]),row("Joel","Joel",3,["Jl"]),row("Amos","Amós",9,["Am"]),row("Obad","Obadias",1,["Ob"]),
row("Jonah","Jonas",4,["Jn"]),row("Mic","Miqueias",7,["Mq"]),row("Nah","Naum",3,["Na"]),row("Hab","Habacuque",3,["Hc"]),row("Zeph","Sofonias",3,["Sf"]),row("Hag","Ageu",2,["Ag"]),
row("Zech","Zacarias",14,["Zc"]),row("Mal","Malaquias",4,["Ml"]),row("Matt","Mateus",28,["Mt"]),row("Mark","Marcos",16,["Mc"]),row("Luke","Lucas",24,["Lc"]),row("John","João",21,["Jo","Joao"]),
row("Acts","Atos",28,["At"]),row("Rom","Romanos",16,["Rm","Rom"]),row("1Cor","1 Coríntios",16,["1Co","1 Corintios"]),row("2Cor","2 Coríntios",13,["2Co","2 Corintios"]),row("Gal","Gálatas",6,["Gl","Galatas"]),
row("Eph","Efésios",6,["Ef","Efesios"]),row("Phil","Filipenses",4,["Fp"]),row("Col","Colossenses",4,["Cl"]),row("1Thess","1 Tessalonicenses",5,["1Ts"]),row("2Thess","2 Tessalonicenses",3,["2Ts"]),
row("1Tim","1 Timóteo",6,["1Tm","1 Timoteo"]),row("2Tim","2 Timóteo",4,["2Tm","2 Timoteo"]),row("Titus","Tito",3,["Tt"]),row("Phlm","Filemom",1,["Fm"]),row("Heb","Hebreus",13,["Hb"]),
row("Jas","Tiago",5,["Tg"]),row("1Pet","1 Pedro",5,["1Pe"]),row("2Pet","2 Pedro",3,["2Pe"]),row("1John","1 João",5,["1Jo","1 Joao"]),row("2John","2 João",1,["2Jo","2 Joao"]),
row("3John","3 João",1,["3Jo","3 Joao"]),row("Jude","Judas",1,["Jd"]),row("Rev","Apocalipse",22,["Ap"])
];
export const BIBLE_SOURCE={id:"almeida-1819-midvash",title:"Almeida 1819 (Bíblia Livre)",organization:"Midvash Bible Data",revision:"d9fe1779447717bbfcb578e505b893125cad581c",license:"public-domain",metadataUrl:"https://github.com/midvash/bible-data/blob/d9fe1779447717bbfcb578e505b893125cad581c/versions/pt/almeida-livre/metadata.json"} as const;
const sourceBase="https://raw.githubusercontent.com/midvash/bible-data/"+BIBLE_SOURCE.revision+"/versions/pt/almeida-livre/books/";const cache=new Map<string,BibleBookData>();export const clearBibleCacheForTests=()=>cache.clear();
function normalize(value:string){return value.replace(/Jó(?=\\s|$)/giu,"Job").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR")}
const aliases=BIBLE_BOOKS.flatMap(book=>book.aliases.map(alias=>({alias:normalize(alias),book}))).sort((a,b)=>b.alias.length-a.alias.length);
const aliasPattern=aliases.map(({alias})=>alias.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|");
const referencePattern=new RegExp("(?:^|[^a-z0-9])("+aliasPattern+")\\s+(\\d{1,3})(?:\\s*[:.]\\s*(\\d{1,3})(?:\\s*[-–]\\s*(\\d{1,3}))?)?","giu");
function unique(items:BibleReference[]){const seen=new Set<string>();return items.filter(item=>{const key=[item.book.osis,item.chapter,item.verseStart??"",item.verseEnd??"",item.origin].join(":");if(seen.has(key))return false;seen.add(key);return true})}
export function parseBibleReferences(text:string,origin:BibleReference["origin"]="question"){const normalized=normalize(text);const found:BibleReference[]=[];referencePattern.lastIndex=0;for(const match of normalized.matchAll(referencePattern)){const book=aliases.find(item=>item.alias===match[1])?.book;if(!book)continue;const chapter=Number(match[2]);const verseStart=match[3]?Number(match[3]):undefined;const verseEnd=match[4]?Number(match[4]):verseStart;const suffix=verseStart?":"+verseStart+(verseEnd&&verseEnd!==verseStart?"-"+verseEnd:""):"";found.push({book,chapter,verseStart,verseEnd,label:book.name+" "+chapter+suffix,origin})}return unique(found)}
const TOPICS=[{test:/bom samaritano/i,reference:"Lucas 10:25-37"},{test:/serm[aã]o do monte/i,reference:"Mateus 5"},{test:/filho pr[oó]digo/i,reference:"Lucas 15:11-32"}];
export function referencesForQuestion(question:string,lessonReference?:string){const direct=parseBibleReferences(question,"question");if(direct.length)return direct;const topic=TOPICS.find(item=>item.test.test(question));if(topic)return parseBibleReferences(topic.reference,"topic");return lessonReference?parseBibleReferences(lessonReference,"lesson"):[]}
function expandCanonicalContext(references:BibleReference[]){const primary=references[0];if(!primary||primary.book.osis!=="Rom"||primary.chapter!==9||primary.verseStart!==undefined)return references;return unique([...references,...parseBibleReferences("Romanos 10:1-4","topic"),...parseBibleReferences("Romanos 11:1-6","topic"),...parseBibleReferences("Romanos 11:25-36","topic")])}
export function invalidReferenceReason(reference:BibleReference){if(reference.chapter<1||reference.chapter>reference.book.chapters)return reference.book.name+" possui "+reference.book.chapters+" capítulo"+(reference.book.chapters===1?"":"s")+", não o capítulo "+reference.chapter+".";if(reference.verseStart!==undefined&&reference.verseStart<1)return"O número do versículo deve ser maior que zero.";if(reference.verseEnd!==undefined&&reference.verseStart!==undefined&&reference.verseEnd<reference.verseStart)return"O intervalo de versículos está invertido.";return undefined}
async function loadBook(book:BibleBook,fetcher:typeof fetch){const saved=cache.get(book.osis);if(saved)return saved;const response=await fetcher(sourceBase+encodeURIComponent(book.osis)+".json",{headers:{accept:"application/json"}});if(!response.ok)throw new Error("bible-source-"+response.status);const data=await response.json() as Partial<BibleBookData>;if(data.book!==book.osis||!Array.isArray(data.chapters))throw new Error("invalid-bible-source");const valid=data.chapters.every(chapter=>Number.isInteger(chapter.chapter)&&Array.isArray(chapter.verses)&&chapter.verses.every(verse=>Number.isInteger(verse.number)&&typeof verse.text==="string"));if(!valid)throw new Error("invalid-bible-source");cache.set(book.osis,data as BibleBookData);return data as BibleBookData}
export interface BibleGrounding{text:string;references:BibleReference[];invalid:{reference:BibleReference;reason:string}[];sourceAvailable:boolean}
export async function retrieveBibleGrounding(question:string,lessonReference?:string,fetcher:typeof fetch=fetch):Promise<BibleGrounding>{const references=expandCanonicalContext(referencesForQuestion(question,lessonReference)).slice(0,4);const invalid=references.flatMap(reference=>{const reason=invalidReferenceReason(reference);return reason?[{reference,reason}]:[]});const excerpts:string[]=[];let sourceAvailable=true;for(const reference of references.filter(item=>!invalidReferenceReason(item))){try{const data=await loadBook(reference.book,fetcher);const chapter=data.chapters.find(item=>item.chapter===reference.chapter);if(!chapter){invalid.push({reference,reason:"O capítulo não foi encontrado na base bíblica verificada."});continue}const start=reference.verseStart??1;const end=Math.min(reference.verseEnd??chapter.verses.at(-1)?.number??start,start+39);const verses=chapter.verses.filter(verse=>verse.number>=start&&verse.number<=end);if(!verses.length||(reference.verseStart&&verses[0]?.number!==reference.verseStart)){invalid.push({reference,reason:reference.label+" não existe na tradução consultada."});continue}excerpts.push("["+reference.label+" — "+BIBLE_SOURCE.title+"]\n"+verses.map(verse=>reference.chapter+":"+verse.number+" "+verse.text).join("\n"))}catch{sourceAvailable=false}}return{text:excerpts.join("\n\n").slice(0,12000),references,invalid,sourceAvailable}}
export async function verifyAnswerReferences(answer:string,fetcher:typeof fetch=fetch){const references=parseBibleReferences(answer,"answer").slice(0,16);const invalid:{label:string;reason:string}[]=[];const grouped=new Map<string,BibleBookData>();for(const reference of references){const shape=invalidReferenceReason(reference);if(shape){invalid.push({label:reference.label,reason:shape});continue}if(reference.verseStart===undefined)continue;try{let data=grouped.get(reference.book.osis);if(!data){data=await loadBook(reference.book,fetcher);grouped.set(reference.book.osis,data)}const chapter=data.chapters.find(item=>item.chapter===reference.chapter);const max=chapter?.verses.at(-1)?.number??0;if(!chapter||reference.verseStart>max||(reference.verseEnd??0)>max)invalid.push({label:reference.label,reason:"A referência não existe na base consultada."})}catch{}}return invalid}
export function invalidQuestionAnswer(grounding:BibleGrounding){const first=grounding.invalid.find(item=>item.reference.origin==="question");if(!first)return undefined;return"A referência **"+first.reference.label+" não existe**. "+first.reason+"\n\nConfira o livro, o capítulo e o versículo e envie a referência corrigida. Não vou inventar conteúdo para uma passagem inexistente."}
