import { invalidQuestionAnswer, retrieveBibleGrounding, verifyAnswerReferences, type BibleGrounding } from "./bible";
import { buildSystemPrompt, classifyTeachingIntent, deterministicSourceLimitation, recommendedMaxTokens, type PolicyInput } from "./policy";
import { applyGroundedSupplements } from "./supplements";

export interface Env {
  GROQ_API_KEY?:string; GEMINI_API_KEY?:string; AI_ENABLED?:string; PRIMARY_PROVIDER?:"groq"|"gemini";
  GROQ_MODEL?:string; GEMINI_MODEL?:string; ALLOWED_ORIGINS?:string; MAX_REQUESTS_PER_DAY?:string;
  MAX_TOKENS_PER_REQUEST?:string; GLOBAL_DAILY_TOKEN_LIMIT?:string; REQUEST_TIMEOUT_MS?:string;
  TURNSTILE_SECRET_KEY?:string; USAGE:KVNamespace;
}
type Provider="groq"|"gemini";
export interface TutorRequest extends PolicyInput { installationId:string; turnstileToken?:string }
const json=(body:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}});
function allowedOrigin(request:Request,env:Env){const origin=request.headers.get("Origin")??"";const allowed=(env.ALLOWED_ORIGINS??"").split(",").map(item=>item.trim()).filter(Boolean);return allowed.includes(origin)?origin:""}
function cors(origin:string):HeadersInit{return{"access-control-allow-origin":origin,"access-control-allow-methods":"POST,OPTIONS","access-control-allow-headers":"content-type","vary":"Origin"}}
function cleanText(value:unknown,max:number){return typeof value==="string"?value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,"").trim().slice(0,max):""}
function cleanLexicalData(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return;const entries=Object.entries(value).slice(0,20).flatMap(([rawKey,rawValue])=>{const key=cleanText(rawKey,80);if(!key)return[];if(Array.isArray(rawValue)){const items=rawValue.slice(0,12).map(item=>cleanText(item,500)).filter(Boolean);return items.length?[[key,items]as const]:[]}const item=cleanText(rawValue,1000);return item?[[key,item]as const]:[]});return entries.length?Object.fromEntries(entries):undefined}
export function validate(body:unknown):TutorRequest|undefined{if(!body||typeof body!=="object")return;const input=body as Partial<TutorRequest>;const modes=["explain","simple","deepen","example","error","practice","ask","pastoral-interview"];const levels=["beginner","intermediate","advanced"];const areas=["bible","greek","lexicon","formation","deepen"];if(!modes.includes(input.mode??"")||!levels.includes(input.level??"")||!input.context||!areas.includes(input.context.area??""))return;const question=cleanText(input.question,1200);const installationId=cleanText(input.installationId,100);const title=cleanText(input.context.title,200);if(!question||!installationId||!title)return;const history=Array.isArray(input.history)?input.history.slice(-8).map(message=>({role:message?.role==="assistant"?"assistant"as const:"user"as const,content:cleanText(message?.content,1500)})).filter(message=>message.content):[];return{question,mode:input.mode!,level:input.level!,installationId,turnstileToken:cleanText(input.turnstileToken,2048)||undefined,history,context:{area:input.context.area,title,objective:cleanText(input.context.objective,600)||undefined,reference:cleanText(input.context.reference,200)||undefined,content:cleanText(input.context.content,6000)||undefined,currentQuestion:cleanText(input.context.currentQuestion,1000)||undefined,selectedAnswer:cleanText(input.context.selectedAnswer,500)||undefined,correctAnswer:cleanText(input.context.correctAnswer,500)||undefined,lexicalData:cleanLexicalData(input.context.lexicalData)}}}
async function verifyTurnstile(request:Request,env:Env,token?:string){if(!env.TURNSTILE_SECRET_KEY)return true;if(!token)return false;const form=new FormData();form.set("secret",env.TURNSTILE_SECRET_KEY);form.set("response",token);form.set("remoteip",request.headers.get("CF-Connecting-IP")??"");const response=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:form});const result=await response.json<{success?:boolean}>();return result.success===true}
const dayKey=()=>new Date().toISOString().slice(0,10);
async function digest(value:string){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
export async function reserveUsage(request:Request,env:Env,input:TutorRequest){const day=dayKey();const identity=await digest((request.headers.get("CF-Connecting-IP")??"unknown")+":"+input.installationId);const userKey="user:"+day+":"+identity;const globalKey="global:"+day;const[userRaw,globalRaw]=await Promise.all([env.USAGE.get(userKey),env.USAGE.get(globalKey)]);const userCount=Number(userRaw??0);const globalTokens=Number(globalRaw??0);const requestLimit=Math.max(1,Number(env.MAX_REQUESTS_PER_DAY??30));const tokenLimit=Math.max(1000,Number(env.GLOBAL_DAILY_TOKEN_LIMIT??200000));if(userCount>=requestLimit)return{ok:false as const,status:429,message:"Limite diário do Noah atingido nesta instalação."};if(globalTokens>=tokenLimit)return{ok:false as const,status:503,message:"O limite global diário do Noah foi atingido."};await env.USAGE.put(userKey,String(userCount+1),{expirationTtl:172800});return{ok:true as const,globalKey,globalTokens}}
export function systemPrompt(input:TutorRequest,grounding:BibleGrounding={text:"",references:[],invalid:[],sourceAvailable:false}){return buildSystemPrompt(input,grounding)}
async function withTimeout(url:string,init:RequestInit,timeoutMs:number){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...init,signal:controller.signal})}finally{clearTimeout(timeout)}}
type ProviderResult={answer:string;tokens:number;incomplete:boolean};
async function callGroq(env:Env,input:TutorRequest,grounding:BibleGrounding,maxTokens:number):Promise<ProviderResult>{if(!env.GROQ_API_KEY)throw new Error("provider-not-configured");const messages=[{role:"system",content:systemPrompt(input,grounding)},...(input.history??[]),{role:"user",content:input.question}];const response=await withTimeout("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{authorization:"Bearer "+env.GROQ_API_KEY,"content-type":"application/json"},body:JSON.stringify({model:env.GROQ_MODEL??"llama-3.3-70b-versatile",messages,temperature:0.15,max_tokens:maxTokens})},Number(env.REQUEST_TIMEOUT_MS??18000));if(!response.ok)throw new Error("groq-"+response.status);const data=await response.json<{choices?:{message?:{content?:string};finish_reason?:string}[];usage?:{total_tokens?:number}}>();const answer=cleanText(data.choices?.[0]?.message?.content,16000);if(!answer)throw new Error("empty-provider-response");return{answer,tokens:data.usage?.total_tokens??maxTokens,incomplete:data.choices?.[0]?.finish_reason==="length"}}
async function callGemini(env:Env,input:TutorRequest,grounding:BibleGrounding,maxTokens:number):Promise<ProviderResult>{if(!env.GEMINI_API_KEY)throw new Error("provider-not-configured");const model=env.GEMINI_MODEL??"gemini-2.5-flash";const contents=[...(input.history??[]),{role:"user"as const,content:input.question}].map(message=>({role:message.role==="assistant"?"model":"user",parts:[{text:message.content}]}));const response=await withTimeout("https://generativelanguage.googleapis.com/v1beta/models/"+encodeURIComponent(model)+":generateContent?key="+encodeURIComponent(env.GEMINI_API_KEY),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:systemPrompt(input,grounding)}]},contents,generationConfig:{temperature:0.15,maxOutputTokens:maxTokens}})},Number(env.REQUEST_TIMEOUT_MS??18000));if(!response.ok)throw new Error("gemini-"+response.status);const data=await response.json<{candidates?:{content?:{parts?:{text?:string}[]};finishReason?:string}[];usageMetadata?:{totalTokenCount?:number}}>();const answer=cleanText(data.candidates?.[0]?.content?.parts?.map(part=>part.text??"").join("\n"),16000);if(!answer)throw new Error("empty-provider-response");return{answer,tokens:data.usageMetadata?.totalTokenCount??maxTokens,incomplete:data.candidates?.[0]?.finishReason==="MAX_TOKENS"}}
async function answerWithFallback(env:Env,input:TutorRequest,grounding:BibleGrounding){const primary:Provider=env.PRIMARY_PROVIDER==="gemini"?"gemini":"groq";const providers:Provider[]=primary==="groq"?["groq","gemini"]:["gemini","groq"];const configured=Math.min(2400,Math.max(100,Number(env.MAX_TOKENS_PER_REQUEST??2400)));const maxTokens=recommendedMaxTokens(classifyTeachingIntent(input),configured);let lastError="unavailable";for(const provider of providers){if(provider==="groq"&&!env.GROQ_API_KEY)continue;if(provider==="gemini"&&!env.GEMINI_API_KEY)continue;for(let attempt=0;attempt<2;attempt++){try{const result=provider==="groq"?await callGroq(env,input,grounding,maxTokens):await callGemini(env,input,grounding,maxTokens);return{...result,provider}}catch(error){lastError=error instanceof Error?error.message:"provider-error";if(lastError==="provider-not-configured"||attempt===1)break;await new Promise(resolve=>setTimeout(resolve,250))}}}throw new Error(lastError)}
async function appendVerification(answer:string,incomplete:boolean,input:TutorRequest,grounding:BibleGrounding){const invalid=await verifyAnswerReferences(answer);let verified=applyGroundedSupplements(answer,input,grounding);if(invalid.length){verified+="\n\n> **Nota de verificação:** estas referências não passaram na validação canônica e não devem ser usadas como base: "+invalid.map(item=>item.label).join(", ")+"."}if(incomplete)verified+="\n\n> **Resposta interrompida pelo limite de tamanho.** Peça ao Noah para continuar a partir deste ponto.";return verified}
export default{async fetch(request:Request,env:Env):Promise<Response>{const origin=allowedOrigin(request,env);if(request.method==="OPTIONS")return origin?new Response(null,{status:204,headers:cors(origin)}):new Response(null,{status:403});if(new URL(request.url).pathname==="/health")return json({ok:true,aiEnabled:env.AI_ENABLED!=="false",grounding:"almeida-1819"});if(request.method!=="POST"||new URL(request.url).pathname!=="/v1/tutor")return json({error:"not-found"},404);if(!origin)return json({error:"origin-not-allowed"},403);if(env.AI_ENABLED==="false")return json({error:"disabled",message:"O Noah está temporariamente desativado."},503,cors(origin));let rawText:string;try{rawText=await request.text()}catch{return json({error:"invalid-body"},400,cors(origin))}if(new TextEncoder().encode(rawText).byteLength>16000)return json({error:"payload-too-large"},413,cors(origin));let raw:unknown;try{raw=JSON.parse(rawText)}catch{return json({error:"invalid-json"},400,cors(origin))}const input=validate(raw);if(!input)return json({error:"invalid-request",message:"A pergunta ou o contexto não são válidos."},400,cors(origin));if(!(await verifyTurnstile(request,env,input.turnstileToken)))return json({error:"challenge-failed"},403,cors(origin));const grounding=await retrieveBibleGrounding(input.question,input.context.reference);const deterministic=invalidQuestionAnswer(grounding);if(deterministic)return json({answer:deterministic,provider:"verified-local",tokens:0,grounding:{references:grounding.references.map(item=>item.label),sourceAvailable:grounding.sourceAvailable}},200,cors(origin));const sourceLimitation=deterministicSourceLimitation(input);if(sourceLimitation)return json({answer:sourceLimitation,provider:"verified-local",tokens:0,grounding:{references:[],sourceAvailable:false}},200,cors(origin));const usage=await reserveUsage(request,env,input);if(!usage.ok)return json({error:"limit",message:usage.message},usage.status,cors(origin));try{const result=await answerWithFallback(env,input,grounding);const answer=await appendVerification(result.answer,result.incomplete,input,grounding);await env.USAGE.put(usage.globalKey,String(usage.globalTokens+result.tokens),{expirationTtl:172800});return json({answer,provider:result.provider,tokens:result.tokens,incomplete:result.incomplete,grounding:{references:grounding.references.map(item=>item.label),sourceAvailable:grounding.sourceAvailable}},200,cors(origin))}catch{return json({error:"provider-unavailable",message:"Noah está indisponível agora. A lição continua funcionando normalmente."},503,cors(origin))}}};
