import { buildGreekUnits, type GreekLessonSeed, type GreekUnitSeed } from "./buildGreekUnits";
const R=(bookId:string,label:string,startChapter:number,startVerse:number,endVerse=startVerse)=>({bookId,label,startChapter,startVerse,endChapter:startChapter,endVerse});
const L=(title:string,subtitle:string,concept:[string,string],reference:ReturnType<typeof R>,teaching:string,practice:string,question:GreekLessonSeed["question"],fill:GreekLessonSeed["fill"],blocks?:GreekLessonSeed["blocks"]):GreekLessonSeed=>({title,subtitle,concept,reference,teaching,practice,question,fill,blocks});
const seeds:GreekUnitSeed[]=[
{id:"greek-u01",title:"Alfabeto grego",subtitle:"Reconheça e escreva as 24 letras",objectives:["Distinguir maiúsculas e minúsculas","Nomear letras e sons de referência","Reconhecer sinais iniciais"],lessons:[
L("As 24 letras","De alfa a ômega",["greek-alphabet","Alfabeto e ordem"],R("revelation","Apocalipse 1:8",1,8),"O alfabeto koiné tem 24 letras: Α α alfa, Β β beta, Γ γ gama, Δ δ delta, Ε ε épsilon, Ζ ζ zeta, Η η eta, Θ θ theta, Ι ι iota, Κ κ kappa, Λ λ lambda, Μ μ mi, Ν ν ni, Ξ ξ xi, Ο ο ómicron, Π π pi, Ρ ρ rho, Σ σ/ς sigma, Τ τ tau, Υ υ ýpsilon, Φ φ phi, Χ χ chi, Ψ ψ psi e Ω ω ômega. Sigma usa ς apenas no fim da palavra.","Leia em grupos de seis. Compare formas parecidas sem depender do alfabeto latino: ν não é v, ρ não é p e η não é n.",["Quantas letras possui o alfabeto grego?","24","22","26","27","O alfabeto grego usado no Novo Testamento possui 24 letras."],["A forma final do sigma é","ς",".","σ","ζ","ξ","ς aparece no fim de palavra; σ aparece nas demais posições."]),
L("Maiúsculas e minúsculas","Pares que mudam de forma",["greek-cases","Formas maiúsculas e minúsculas"],R("john","João 1:1",1,1),"Alguns pares são visualmente próximos, como Α/α e Κ/κ; outros mudam bastante, como Γ/γ, Δ/δ, Λ/λ e Ω/ω. Manuscritos antigos podiam usar escrita maiúscula contínua, enquanto edições modernas empregam minúsculas, espaços e sinais editoriais.","Treine a correspondência, não o desenho isolado. Em λόγος, identifique lambda, ómicron, gama, ómicron e sigma final.",["Qual é a minúscula de Ω?","ω","ο","σ","η","Ω e ω são as formas de ômega."],["Em λόγος, a primeira letra é","lambda",".","gama","rho","tau","λ é lambda e inicia λόγος."]),
L("Sons de referência","Pronúncia como ferramenta de leitura",["greek-sounds","Sons básicos de referência"],R("matthew","Mateus 1:1",1,1),"Pronúncias erasmiana, reconstruída e moderna diferem. O curso usa uma pronúncia pedagógica de referência e sinaliza que ela não é gravação exata do século I. β, γ, δ, θ, φ e χ exigem atenção; γ muda diante de γ, κ, ξ e χ.","A meta inicial é associar grafema e som de forma consistente. Pronúncia ajuda memória, mas a análise gramatical não depende de escolher uma única tradição.",["Qual afirmação é mais responsável sobre a pronúncia koiné?","Há sistemas legítimos diferentes","Existe uma gravação exata do século I","Toda letra soa como em português","Pronúncia não ajuda a leitura","Reconstruções e tradições pedagógicas diferem; o curso declara sua convenção."],["A pronúncia é uma ferramenta de","leitura",".","inspiração","tradução automática","doutrina","Ela apoia reconhecimento e fluência, não decide sozinha o sentido."]),
L("Diacríticos iniciais","Acentos, espíritos e iota subscrito",["greek-diacritics","Reconhecimento de diacríticos"],R("john","João 1:1",1,1),"Edições modernas usam acento agudo, grave e circunflexo; espírito brando e áspero marcam o início vocálico, e o áspero indica som de h na pronúncia erasmiana. O iota subscrito pode aparecer sob α, η ou ω longos.","Neste momento, reconheça os sinais sem tentar dominar todas as regras. Em ὁ, note espírito áspero; em ἀρχή, espírito brando e acento.",["Qual sinal indica aspiração na convenção erasmiana?","Espírito áspero","Espírito brando","Iota subscrito","Ponto alto","O espírito áspero marca aspiração inicial."],["Em ἀρχή, o primeiro sinal é espírito","brando",".","áspero","circunflexo","final","A forma ἀ começa com espírito brando."])
]},
{id:"greek-u02",title:"Leitura e pronúncia",subtitle:"Combine sons e divida palavras",objectives:["Reconhecer vogais e ditongos","Ler consoantes e encontros","Identificar sílabas e sinais"],lessons:[
L("Vogais e quantidade","Sete vogais gregas",["greek-vowels","Vogais e quantidade"],R("john","João 1:1",1,1),"As vogais são α, ε, η, ι, ο, υ, ω. ε e ο são sempre breves; η e ω são sempre longas; α, ι e υ podem ser breves ou longas. Quantidade vocálica ajuda a entender acentuação, mas nem sempre aparece graficamente.","Leia θεός separando θε-ός. Não confunda η com a letra latina n nem υ com u português em todos os sistemas.",["Quais vogais são sempre longas?","η e ω","ε e ο","α e ι","ο e υ","Eta e ômega são vogais longas por natureza."],["As vogais sempre breves são","ε e ο",".","η e ω","α e υ","ι e ω","Épsilon e ómicron são breves."]),
L("Ditongos","Duas vogais em uma unidade",["greek-diphthongs","Ditongos frequentes"],R("john","João 1:1–3",1,1,3),"Ditongos frequentes incluem αι, ει, οι, αυ, ευ, ου e υι. Em geral, suas vogais pertencem à mesma sílaba. A diaérese pode indicar que devem ser lidas separadamente.","Em αὐτός, αυ forma ditongo. Em Ἰησοῦς, observe a sequência e os sinais antes de dividir mecanicamente.",["Qual par é um ditongo frequente?","ου","εα","οη","αο","ου funciona regularmente como unidade vocálica."],["Em αὐτός, a primeira unidade vocálica é","αυ",".","α","υο","ος","Alfa e ýpsilon formam o ditongo αυ."]),
L("Consoantes e encontros","Oclusivas, líquidas e duplas",["greek-consonants","Classes consonantais"],R("mark","Marcos 1:1",1,1),"π β φ são labiais; κ γ χ, velares; τ δ θ, dentais. λ e ρ são líquidas; μ e ν, nasais. ζ, ξ e ψ representam combinações historicamente complexas; ξ costuma corresponder a ks e ψ a ps.","Agrupar letras explica mudanças morfológicas posteriores. Quando uma raiz termina em labial diante de sigma, a escrita pode resultar em ψ.",["Que letra representa normalmente o encontro ps?","ψ","ξ","ζ","χ","Psi é convencionalmente lida como ps."],["As letras κ, γ e χ formam o grupo das","velares",".","labiais","nasais","vogais","São articuladas na região velar."]),
L("Sílabas e leitura","Do sinal à palavra",["greek-syllables","Divisão silábica"],R("john","João 1:1",1,1),"Cada sílaba possui uma vogal ou ditongo. Uma única consoante entre vogais tende a iniciar a sílaba seguinte; grupos consonantais exigem observar se podem iniciar palavra grega. Pontuação moderna ajuda a leitura de períodos.","Divida λόγος como λό-γος e ἀρχή como ἀρ-χή. Leia devagar, mantendo o acento como auxílio, não como substituto da forma.",["Quantos núcleos silábicos há em λόγος?","Dois","Um","Três","Quatro","As vogais ό e ο formam dois núcleos: λό-γος."],["A divisão pedagógica de λόγος é","λό-γος",".","λ-όγος","λόγ-ος","λο-γο-ς","Cada sílaba contém seu núcleo vocálico."])
]},
{id:"greek-u03",title:"Vocabulário fundamental",subtitle:"Palavras frequentes do Novo Testamento",objectives:["Reconhecer classes frequentes","Aprender lemas em contexto","Evitar equivalência rígida"],lessons:[
L("Artigo e palavras funcionais","ὁ, ἡ, τό e conexões",["greek-articles","Artigo e palavras funcionais"],R("john","João 1:1",1,1),"O artigo varia em gênero, número e caso: ὁ, ἡ, τό são formas nominativas singulares. καί pode significar e, também ou até conforme o contexto; δέ frequentemente conecta com nuance leve de contraste ou continuidade.","Palavras pequenas estruturam a frase. Não traduza mecanicamente cada artigo, pois grego e português usam artigos de maneiras diferentes.",["Qual é a forma nominativa singular feminina do artigo?","ἡ","ὁ","τό","οἱ","ἡ acompanha substantivos femininos nominativos singulares."],["καί frequentemente funciona como","conjunção",".","substantivo","artigo","verbo","Seu valor básico conecta elementos, com nuance definida pelo contexto."]),
L("Substantivos frequentes","θεός, λόγος, ζωή, ἐκκλησία",["greek-nouns","Lemas nominais frequentes"],R("john","João 1:1–4",1,1,4),"θεός pode designar Deus ou um deus conforme contexto; λόγος inclui palavra, mensagem, discurso ou razão; ζωή é vida; ἐκκλησία é assembleia ou comunidade. O lema é a forma de dicionário, não necessariamente a forma vista no texto.","Aprenda lema, gênero e faixa de sentidos. O contexto e a sintaxe escolhem uma tradução adequada entre possibilidades legítimas.",["Qual lema corresponde a 'vida'?","ζωή","λόγος","θεός","πίστις","STEP TBESG registra ζωή (G2222) com a glosa básica life."],["O lema λόγος não deve receber sempre a mesma","tradução",".","acentuação","letra inicial","classe","Seu sentido é delimitado pelo uso contextual."]),
L("Verbos frequentes","εἰμί, λέγω, πιστεύω, ἀγαπάω",["greek-verbs","Lemas verbais frequentes"],R("john","João 3:16",3,16),"εἰμί é ser/estar; λέγω, dizer; πιστεύω, crer ou confiar; ἀγαπάω, amar. Dicionários apresentam verbos geralmente na primeira pessoa singular do presente ativo, não no infinitivo português.","Ao encontrar λέγει, procure o lema λέγω. A forma flexionada comunica pessoa, número e outros valores além do significado lexical.",["Qual lema está por trás de λέγει?","λέγω","λόγος","εἰμί","ἀγαπάω","λέγει é forma flexionada do verbo λέγω."],["A forma de dicionário de um verbo grego costuma ser a primeira pessoa do","presente",".","aoristo","futuro","infinitivo","A convenção lexical usa normalmente o presente indicativo ativo, primeira singular."]),
L("Preposições e pronomes","Relações marcadas pelo caso",["greek-prepositions","Preposições e pronomes"],R("john","João 1:1–2",1,1,2),"ἐν costuma ocorrer com dativo; εἰς, com acusativo; ἐκ, com genitivo. αὐτός pode funcionar como ele/ela/isso, mesmo ou, em certos contextos, com valor próximo ao pronome pessoal.","Preposição e caso formam conjunto. Não determine o sentido apenas pela lista do dicionário: observe a construção inteira.",["Qual preposição costuma reger acusativo?","εἰς","ἐν","ἐκ","ἀπό","εἰς aparece regularmente com acusativo e expressa movimento ou direção, entre outros usos."],["Para analisar uma preposição, observe também o","caso",".","tamanho da palavra","número de letras","tipo de acento apenas","O caso ajuda a delimitar a relação sintática."])
]},
{id:"greek-u04",title:"Estrutura nominal",subtitle:"Gênero, número, caso e declinações",objectives:["Identificar valores de caso","Reconhecer concordância","Analisar formas nominais"],lessons:[
L("Gênero e número","Masculino, feminino, neutro",["greek-gender-number","Gênero e número gramaticais"],R("john","João 1:1",1,1),"O grego possui gêneros masculino, feminino e neutro, além de singular e plural. Gênero gramatical não é sempre sexo natural. Artigo, adjetivo e substantivo concordam em gênero, número e caso.","Aprenda substantivo com artigo: ὁ λόγος, ἡ ζωή, τό ἔργον. O artigo ajuda a memorizar gênero e reconhecer formas.",["Qual é o gênero de ζωή quando aparece com ἡ?","Feminino","Masculino","Neutro","Comum","O artigo ἡ indica feminino nominativo singular."],["Artigo e substantivo concordam em gênero, número e","caso",".","tempo","voz","aspecto","Essas três categorias estruturam a concordância nominal."]),
L("Nominativo e vocativo","Sujeito e chamamento",["greek-nominative","Nominativo e vocativo"],R("john","João 1:1",1,1),"O nominativo frequentemente marca o sujeito ou predicativo. O vocativo é usado em chamamento direto e pode ter forma própria, como κύριε, 'ó Senhor'. Função é confirmada pela frase, não apenas pela terminação.","Em θεὸς ἦν ὁ λόγος, as formas nominativas participam de uma construção predicativa cuja ordem exige análise cuidadosa.",["Qual caso é típico do chamamento direto?","Vocativo","Genitivo","Dativo","Acusativo","O vocativo dirige-se a alguém diretamente."],["O caso frequente do sujeito é o","nominativo",".","vocativo","genitivo","dativo","Nominativo é a marca mais comum do sujeito expresso."]),
L("Genitivo e dativo","Relação, esfera e participante",["greek-genitive-dative","Genitivo e dativo"],R("ephesians","Efésios 2:8",2,8),"O genitivo pode marcar posse, origem, relação e muitas outras nuances. O dativo pode indicar recipiente, instrumento, esfera ou localização. Rótulos simples ajudam no início, mas não esgotam os usos.","Em χάριτί ἐστε σεσῳσμένοι, χάριτι é dativo; a tradução 'pela graça' interpreta seu papel na construção.",["Qual forma está no dativo em Efésios 2:8?","χάριτι","πίστεως","θεός","λόγος","χάριτι é dativo singular de χάρις."],["O genitivo não significa apenas","posse",".","relação","origem","descrição","Ele possui ampla variedade de relações contextuais."]),
L("Acusativo e declinações","Objeto e paradigmas",["greek-accusative","Acusativo e padrões de declinação"],R("john","João 3:16",3,16),"O acusativo marca frequentemente objeto direto e extensão. Primeira, segunda e terceira declinações agrupam padrões de flexão; não são níveis de importância. A terceira reúne maior variedade de temas.","Compare ὁ λόγος, τοῦ λόγου, τῷ λόγῳ, τὸν λόγον. Terminação, artigo e função colaboram na análise.",["Em τὸν λόγον, qual caso é indicado?","Acusativo","Nominativo","Genitivo","Dativo","τὸν e -ον marcam acusativo masculino singular."],["As declinações agrupam padrões de","flexão",".","inspiração","pronúncia moderna","tradução","Elas organizam terminações nominais."])
]},
{id:"greek-u05",title:"Estrutura verbal",subtitle:"Pessoa, aspecto, voz e modo",objectives:["Separar aspecto de referência temporal","Identificar voz e modo","Reconhecer formas verbais"],lessons:[
L("Pessoa e número","Quem participa do processo",["greek-person","Pessoa e número verbais"],R("john","João 1:1",1,1),"Terminações verbais comunicam primeira, segunda ou terceira pessoa e singular ou plural. λέγω é 'eu digo'; λέγει pode ser 'ele/ela diz'. O sujeito pode estar contido na forma verbal.","Antes de traduzir, identifique a terminação. Não presuma que toda forma sem pronome tenha sujeito indefinido.",["Que pessoa e número λέγει normalmente marca?","Terceira singular","Primeira singular","Segunda plural","Terceira plural","A terminação -ει no presente ativo indica terceira singular."],["A forma verbal grega pode incluir informação sobre o","sujeito",".","artigo","gênero do autor","número de Strong","Pessoa e número fazem parte da flexão."]),
L("Tempo e aspecto","Não confundir categorias",["greek-aspect","Aspecto verbal e referência temporal"],R("mark","Marcos 1:11",1,11),"As formas chamadas presente, imperfeito, aoristo, perfeito e futuro combinam aspecto e, em certos modos, referência temporal. O aoristo apresenta a ação de modo global; isso não significa automaticamente ação instantânea ou 'uma vez por todas'.","No indicativo, aumento e forma verbal contribuem para referência passada. Fora do indicativo, o aspecto costuma ser mais central que tempo cronológico.",["Qual afirmação sobre o aoristo é correta?","Apresenta a ação de modo global","Sempre significa uma ação instantânea","Sempre significa uma vez por todas","Nunca se refere ao passado","O aoristo não carrega por si só as simplificações populares."],["Aspecto descreve como o autor apresenta o","processo",".","alfabeto","gênero nominal","manuscrito","Ele oferece uma perspectiva sobre a ação ou estado."]),
L("Voz","Ativa, média e passiva",["greek-voice","Voz verbal"],R("ephesians","Efésios 2:8",2,8),"A voz ativa apresenta o sujeito realizando o processo; a passiva, recebendo-o. A voz média destaca participação do sujeito e possui usos próprios; não deve ser reduzida sempre a ação reflexiva. Algumas formas são morfologicamente ambíguas entre média e passiva.","σεσῳσμένοι é particípio perfeito médio/passivo no paradigma; o contexto de Efésios favorece leitura passiva: 'tendo sido salvos'.",["Qual voz apresenta o sujeito recebendo a ação?","Passiva","Ativa","Vocativa","Genitiva","A passiva perfila o sujeito como paciente."],["A voz média não é sempre simplesmente","reflexiva",".","verbal","grega","flexionada","Ela possui gama de usos e exige contexto."]),
L("Modo e verbos irregulares","Indicativo, subjuntivo, imperativo e optativo",["greek-mood","Modo verbal"],R("matthew","Mateus 6:9",6,9),"O indicativo costuma fazer afirmações; o subjuntivo aparece em possibilidades, propósito e exortação; o imperativo em comandos; o optativo é raro no Novo Testamento. εἰμί possui formas irregulares frequentes e deve ser aprendido cedo.","Modo não equivale ao tom emocional. Observe partículas como ἵνα e μή, que ajudam a interpretar a construção.",["Qual modo é raro no Novo Testamento?","Optativo","Indicativo","Subjuntivo","Imperativo","O optativo sobrevive, mas é bem menos frequente."],["εἰμί é um verbo frequente e","irregular",".","inexistente","sempre passivo","sem pessoa","Suas formas exigem memorização específica."])
]},
{id:"greek-u06",title:"Construção de frases",subtitle:"Sintaxe básica e ordem flexível",objectives:["Analisar concordância","Reconhecer negação e perguntas","Ler frases nominais e verbais"],lessons:[
L("Ordem das palavras","Flexão e destaque",["greek-word-order","Ordem e ênfase"],R("john","João 1:1",1,1),"Como as terminações marcam funções, a ordem grega é mais flexível que a portuguesa, mas não aleatória. Posição pode contribuir para tópico, foco, contraste e estilo. Não transforme automaticamente a primeira palavra em sujeito.","Em καὶ θεὸς ἦν ὁ λόγος, o artigo ajuda a identificar ὁ λόγος como sujeito, enquanto θεός funciona predicativamente.",["O que ajuda a identificar o sujeito em João 1:1c?","O artigo com ὁ λόγος","A primeira posição apenas","O acento de θεός","O tamanho das palavras","A marcação do artigo contribui para a análise sintática."],["Ordem flexível não significa ordem","aleatória",".","grega","visível","acentuada","Sintaxe e discurso condicionam a posição."]),
L("Concordância","Elementos que caminham juntos",["greek-agreement","Concordância nominal e verbal"],R("matthew","Mateus 5:3",5,3),"Artigos e adjetivos concordam com substantivos em gênero, número e caso. Verbos finitos concordam com o sujeito em pessoa e número, com algumas construções especiais, como sujeito neutro plural com verbo singular.","Agrupe formas que compartilham marcas. Isso ajuda mesmo quando palavras relacionadas não estão lado a lado.",["Em que categorias o adjetivo concorda com o substantivo?","Gênero, número e caso","Tempo, voz e modo","Pessoa e tempo","Acento e espírito","A concordância nominal usa gênero, número e caso."],["O verbo finito concorda normalmente em pessoa e","número",".","caso","gênero","declinação","Pessoa e número vinculam sujeito e verbo."]),
L("Negação e perguntas","οὐ, μή e sinais interrogativos",["greek-negation","Negação e interrogação"],R("john","João 1:3",1,3),"οὐ nega com frequência afirmações no indicativo; μή aparece com modos não indicativos e construções de proibição, condição ou expectativa. O ponto e vírgula grego (;) funciona como sinal de pergunta.","A escolha entre οὐ e μή depende da construção, não de uma diferença simples entre negação forte e fraca.",["Qual sinal moderno marca pergunta em grego?",";","?",":","!","O ponto e vírgula grego desempenha função interrogativa."],["μή ocorre frequentemente com construções não","indicativas",".","nominais","alfabéticas","lexicais","Modo e tipo de oração influenciam a negação."]),
L("Frases nominais e verbais","Predicação com e sem cópula",["greek-clauses","Predicação básica"],R("john","1 João 4:8",4,8),"Frases verbais têm um verbo lexical como núcleo. Frases nominais podem usar εἰμί como cópula ou omiti-la em certos contextos. Predicativos descrevem ou identificam o sujeito, e o artigo pode ajudar a distinguir funções.","Em ὁ θεὸς ἀγάπη ἐστίν, 'Deus é amor', ἀγάπη é predicativo, não uma afirmação reversível de que todo amor seja Deus.",["Qual é o predicativo em ὁ θεὸς ἀγάπη ἐστίν?","ἀγάπη","ὁ","θεός apenas","ἐστίν","ἀγάπη atribui a qualidade ao sujeito ὁ θεός."],["A cópula frequente vem do verbo","εἰμί",".","λέγω","γράφω","λύω","εἰμί liga sujeito e predicativo."])
]},
{id:"greek-u07",title:"Leitura do Novo Testamento",subtitle:"Morfologia e tradução guiada",objectives:["Identificar formas flexionadas","Produzir tradução contextual","Comparar traduções com cuidado"],lessons:[
L("Da forma ao lema","Análise morfológica em etapas",["greek-parsing","Forma, lema e análise"],R("john","João 1:1",1,1),"Analisar uma forma envolve: identificar classe, propor lema, reconhecer flexão e testar a função no contexto. λόγου é genitivo singular de λόγος; θεῷ é dativo singular de θεός. Forma encontrada e lema devem permanecer distintos.","Não procure λόγου como se fosse outro vocábulo. Use terminação e contexto para chegar a λόγος sem apagar a informação do genitivo.",["Qual é o lema de λόγου?","λόγος","λέγω","λογή","λόγου","λόγου é forma flexionada; o lema nominal é λόγος."],["λόγου é genitivo","singular",".","plural","dual","verbal","A terminação -ου marca aqui genitivo singular de segunda declinação."]),
L("João 1:1 guiado","Sintaxe antes da teologia",["greek-john-one","Leitura guiada de João 1:1"],R("john","João 1:1",1,1),"Ἐν ἀρχῇ marca esfera temporal; ἦν é imperfeito de εἰμί; ὁ λόγος é sujeito articulado. πρὸς τὸν θεόν expressa relação. Na cláusula final, θεός é predicativo anteposto e ὁ λόγος continua sujeito.","A gramática informa a leitura, mas debates cristológicos não devem ser resolvidos por slogans sobre ausência de artigo. Sintaxe, contexto e uso do autor caminham juntos.",["Qual forma é imperfeito de εἰμί em João 1:1?","ἦν","ἐν","λόγος","πρός","ἦν ocorre três vezes e apresenta existência continuada no quadro narrativo."],["Na cláusula final, o sujeito articulado é","ὁ λόγος",".","θεός","ἐν","ἀρχή","O artigo e o contexto identificam o sujeito."]),
L("Efésios 2:8 guiado","Dativo, particípio e fé",["greek-ephesians","Leitura guiada de Efésios 2:8"],R("ephesians","Efésios 2:8",2,8),"τῇ γὰρ χάριτί ἐστε σεσῳσμένοι διὰ πίστεως: χάριτι é dativo singular de χάρις; ἐστε é segunda plural de εἰμί; σεσῳσμένοι é particípio perfeito passivo, formando perífrase; διὰ com genitivo marca meio.","A construção distingue graça, salvação e fé sem transformar cada caso em sistema teológico completo por si só.",["Qual forma significa 'vocês são/estão'?","ἐστε","χάριτι","πίστεως","σεσῳσμένοι","ἐστε é segunda pessoa plural do presente de εἰμί."],["διὰ πίστεως usa o caso","genitivo",".","acusativo","dativo","vocativo","πίστεως é genitivo singular de πίστις."]),
L("Comparar traduções","Decisões, não espelhos perfeitos",["greek-translation","Tradução responsável"],R("philippians","Filipenses 2:5",2,5),"Traduções equilibram forma, sentido, clareza e tradição. Diferenças podem refletir variante textual, análise sintática ou escolha estilística. Uma tradução mais literal não é automaticamente mais correta em todo contexto.","Compare qual problema cada versão tenta resolver. Consulte o texto, notas e léxico, e declare quando mais de uma solução é plausível.",["Por que traduções legítimas podem divergir?","Porque precisam tomar decisões contextuais","Porque o grego não tem gramática","Porque toda tradução é falsa","Porque Strong substitui o contexto","Forma, sintaxe, semântica e estilo exigem decisões."],["Uma glosa de dicionário não substitui o","contexto",".","alfabeto","número de letras","acento","Tradução requer uso na frase e no discurso."])
]},
{id:"greek-u08",title:"Grego intermediário",subtitle:"Formas não finitas e períodos complexos",objectives:["Reconhecer particípios e infinitivos","Mapear subordinadas","Iniciar exegese com limites"],lessons:[
L("Particípios","Forma verbal com função adjetiva",["greek-participles","Particípios e circunstâncias"],R("matthew","Mateus 28:19",28,19),"Particípios possuem tempo/aspecto e voz, mas também gênero, número e caso. Podem funcionar substantivados, atributivos, predicativos ou circunstanciais. Sua relação com o verbo principal deve ser inferida pela sintaxe e contexto.","Em πορευθέντες μαθητεύσατε, o particípio aoristo acompanha o imperativo 'fazei discípulos'. Traduzi-lo exige considerar a força do comando principal.",["Que categorias nominais um particípio possui?","Gênero, número e caso","Somente pessoa","Artigo e Strong","Nenhuma flexão","Como forma verbal adjetiva, o particípio recebe marcas nominais."],["O particípio também comunica aspecto e","voz",".","declinação apenas","artigo","pontuação","Ele combina propriedades verbais e nominais."]),
L("Infinitivos","Ação sem pessoa gramatical",["greek-infinitives","Infinitivo e função"],R("philippians","Filipenses 1:21",1,21),"O infinitivo não marca pessoa e pode funcionar como complemento, finalidade, resultado ou substantivo verbal. Pode ter sujeito no acusativo em certas construções e apresenta aspecto e voz.","Identifique primeiro o verbo que governa o infinitivo. Depois pergunte se ele completa, explica propósito ou exerce outra função.",["O infinitivo grego marca pessoa?","Não","Sempre primeira","Sempre terceira","Somente no aoristo","Infinitivos não flexionam por pessoa."],["O infinitivo pode expressar finalidade conforme o","contexto",".","alfabeto","gênero do autor","número de capítulo","A função nasce da construção."]),
L("Orações subordinadas","Conectores e relações",["greek-subordination","Subordinação e conectores"],R("john","João 3:16–17",3,16,17),"ἵνα introduz frequentemente finalidade ou resultado e costuma reger subjuntivo; ὅτι pode introduzir conteúdo ou causa; εἰ marca condições; ὅς introduz oração relativa. Nenhuma partícula possui uma única tradução invariável.","Mapeie verbos e conectores antes de traduzir. Isso revela o esqueleto do período e reduz decisões baseadas apenas em palavras isoladas.",["Qual conector costuma introduzir finalidade com subjuntivo?","ἵνα","καί","ὁ","οὐ","ἵνα é marcador frequente de propósito ou resultado."],["ὅτι pode introduzir conteúdo ou","causa",".","vocativo","alfabeto","declinação","Seu valor depende da relação entre as orações."]),
L("Introdução à exegese","Da análise à interpretação responsável",["greek-exegesis","Exegese linguística com limites"],R("philippians","Filipenses 2:5–11",2,5,11),"Exegese responsável reúne crítica textual, morfologia, sintaxe, semântica, gênero literário, contexto histórico e teologia bíblica. Conhecer grego ajuda a fazer perguntas melhores, não concede interpretação infalível.","Registre evidência, alternativas e grau de certeza. Evite falácia da raiz, soma de todos os sentidos e afirmações de que 'o original realmente diz' algo ausente do contexto.",["Qual prática é uma falácia lexical?","Somar todos os sentidos possíveis numa ocorrência","Analisar sintaxe","Comparar contextos","Declarar incerteza","Uma ocorrência não carrega automaticamente toda a história semântica do lema."],["Conhecer grego ajuda a formular perguntas mais","precisas",".","infalíveis","secretas","denominacionais","A língua é ferramenta, não atalho para certeza absoluta."])
]}
];
export const greekUnits=buildGreekUnits(seeds);
export const greekLessons=greekUnits.flatMap((unit)=>unit.lessons);
export const greekActivityIds=greekUnits.flatMap((unit)=>[...unit.lessons.map((lesson)=>lesson.id),unit.checkpoint.id]);
export const greekActivities=[...greekLessons,...greekUnits.map((unit)=>unit.checkpoint)];
export const greekActivityById=new Map(greekActivities.map((activity)=>[activity.id,activity]));
export const greekUnitByActivityId=new Map(greekUnits.flatMap((unit)=>[...unit.lessons.map((lesson)=>[lesson.id,unit] as const),[unit.checkpoint.id,unit] as const]));
export const greekExercises=greekUnits.flatMap((unit)=>[...unit.lessons.flatMap((lesson)=>lesson.steps.filter((step):step is import("../../types/content").Exercise=>step.type!=="learn")), ...unit.checkpoint.exercises]);
export const greekExerciseById=new Map(greekExercises.map((exercise)=>[exercise.id,exercise]));
