import { buildHistoricalUnits, type HistoricalLessonSeed, type HistoricalUnitSeed } from "../historical/buildHistoricalUnits";

const L = (
  title: string, reference: HistoricalLessonSeed["reference"], concept: [string, string],
  teaching: string, formation: string,
  question: HistoricalLessonSeed["question"], fill: HistoricalLessonSeed["fill"]
): HistoricalLessonSeed => ({ title, reference, concept, teaching, formation, question, fill });

const seeds: HistoricalUnitSeed[] = [
  { id: "joshua-u01", title: "Entrar na promessa", subtitle: "Preparação, travessia e memória em Josué 1–5", chapters: [1,2,3,4,5], lessons: [
    L("Sê forte e corajoso", ["Josué 1",1,1,1,18], ["joshua-courage-word","Coragem orientada pela Palavra"], "Após a morte de Moisés, Deus comissiona Josué. A promessa de presença acompanha a ordem de meditar e praticar a instrução recebida; coragem não é autoconfiança vazia.", "Liderança fiel une dependência de Deus, atenção às Escrituras e responsabilidade comunitária.", ["Em que Josué deveria meditar dia e noite?","No livro da Lei","Em estratégias egípcias","Nas riquezas de Canaã","Nos feitos pessoais","Josué 1:8 liga meditação, prática e caminho responsável."], ["A coragem de Josué deveria ser guiada pela","Palavra",".","força militar","fama","riqueza","A presença de Deus e a instrução sustentam sua missão."]),
    L("Raabe acolhe os espias", ["Josué 2",2,1,2,24], ["joshua-rahab-faith","Fé corajosa de Raabe"], "Raabe reconhece o Deus de Israel, protege os mensageiros e pede misericórdia para sua casa. Sua posição social e origem não impedem uma resposta de fé que muda seu futuro.", "A história mostra graça atravessando fronteiras e valoriza uma mulher estrangeira como participante ativa.", ["Que sinal marcaria a casa de Raabe?","Um cordão escarlate","Uma vara de amendoeira","Uma lâmpada de ouro","Uma faixa azul","O cordão na janela identificaria a casa no momento da tomada da cidade."], ["Raabe confessou que o SENHOR é Deus em cima nos céus e embaixo na","terra",".","arca","cidade","tenda","Josué 2:11 registra sua confissão de fé."]),
    L("O Jordão se abre", ["Josué 3–4",3,1,4,24], ["joshua-jordan-memory","Travessia e memória comunitária"], "A arca segue à frente e o Jordão é atravessado em seco. Doze pedras são levantadas para que as crianças perguntem e a nova geração ouça o que Deus fez.", "Memoriais bíblicos não são amuletos; servem ao ensino, à gratidão e ao testemunho entre gerações.", ["Por que foram levantadas doze pedras?","Para lembrar e ensinar a travessia","Para construir um palácio","Para marcar uma sepultura","Para pesar a arca","Josué 4 explica que as pedras provocariam perguntas e preservariam a memória."], ["As pedras ajudariam os filhos a conhecer a ação de","Deus",".","Faraó","Balaão","Golias","A memória é transmitida por explicação comunitária."]),
    L("Aliança antes da batalha", ["Josué 5",5,1,5,15], ["joshua-covenant-preparation","Consagração antes da conquista"], "Antes de Jericó, a nova geração é circuncidada, celebra a Páscoa e passa a comer do fruto da terra. Josué encontra o comandante do exército do SENHOR e tira as sandálias.", "O texto desloca o foco da capacidade militar para aliança, santidade e submissão à direção divina.", ["O que Israel celebrou antes de enfrentar Jericó?","A Páscoa","Pentecostes","Purim","A dedicação do templo","Josué 5:10 situa a Páscoa na preparação espiritual do povo."], ["Josué tirou as sandálias porque o lugar era","santo",".","secreto","perigoso","estrangeiro","O encontro ecoa o chamado de Moisés e chama à reverência."])
  ]},
  { id: "joshua-u02", title: "Conquista e consequências", subtitle: "Jericó, Ai e a renovação da aliança em Josué 6–8", chapters: [6,7,8], lessons: [
    L("Jericó cai", ["Josué 6",6,1,6,27], ["joshua-jericho","Vitória recebida e juízo narrativo"], "Israel marcha conforme a ordem recebida, e os muros caem após o toque das trombetas. Raabe e sua família são preservadas conforme a promessa dos espias.", "A narrativa pertence à entrada de Israel na terra e não autoriza a igreja a praticar conquista religiosa ou violência.", ["Quem foi preservado em Jericó por causa da promessa?","Raabe e sua casa","O rei de Jericó","Acã e sua casa","Os amalequitas","Josué 6 honra o compromisso assumido com Raabe."], ["A queda dos muros foi apresentada como ação de","Deus",".","Acã","Egito","Gibeão","A estratégia incomum impede que Israel atribua a vitória apenas à força."]),
    L("O pecado de Acã", ["Josué 7",7,1,7,26], ["joshua-achan","Responsabilidade e pecado oculto"], "A derrota em Ai revela que Acã tomou objetos proibidos. Seu ato particular produz consequência coletiva em uma comunidade de aliança.", "O episódio é severo e deve ser lido em seu contexto antigo; ensina que cobiça encoberta corrói a confiança coletiva.", ["O que Acã confessou ter tomado?","Capa, prata e ouro","A arca da aliança","As trombetas","O mapa de Canaã","Josué 7:21 descreve sua cobiça e ocultação."], ["O pecado escondido afetou toda a","comunidade",".","colheita apenas","família de Raabe","cidade de Gibeão","A narrativa ressalta solidariedade e responsabilidade da aliança."]),
    L("Ai e uma nova oportunidade", ["Josué 8:1–29",8,1,8,29], ["joshua-ai-restoration","Correção, estratégia e restauração"], "Depois de tratar o pecado, Israel recebe nova ordem para enfrentar Ai, agora com uma estratégia de emboscada. A derrota anterior não encerra a missão.", "Restauração não ignora responsabilidade; ela aprende com o fracasso e volta a obedecer com prudência.", ["Que estratégia foi usada contra Ai?","Uma emboscada","Sete voltas diárias por um mês","Uma aliança por casamento","Uma fuga para o Egito","Josué 8 descreve uma emboscada atrás da cidade."], ["Depois da correção, Israel pôde","recomeçar",".","esconder o erro","abandonar Josué","voltar ao Egito","Deus renova a missão sem tratar o fracasso como palavra final."]),
    L("A lei lida no monte", ["Josué 8:30–35",8,30,8,35], ["joshua-ebal-covenant","Renovação pública da aliança"], "Josué edifica altar, escreve uma cópia da lei e lê bênçãos e maldições diante de toda a assembleia, incluindo mulheres, crianças e estrangeiros.", "A vida na terra deve ser governada pela aliança e incluir toda a comunidade na escuta.", ["Quem ouviu a leitura da lei?","Toda a assembleia, incluindo estrangeiros","Somente guerreiros","Apenas sacerdotes","Somente líderes tribais","Josué 8:35 enfatiza a amplitude da assembleia."], ["A conquista é interrompida para renovar a","aliança",".","muralha","emboscada","monarquia","A Palavra interpreta a vida do povo na terra."])
  ]},
  { id: "joshua-u03", title: "Discernir alianças", subtitle: "Gibeão e a campanha do sul e do norte em Josué 9–12", chapters: [9,10,11,12], lessons: [
    L("O engano dos gibeonitas", ["Josué 9",9,1,9,27], ["joshua-gibeon","Discernimento e palavra empenhada"], "Os gibeonitas simulam uma longa viagem. Os líderes examinam provisões, mas não consultam o SENHOR, e fazem aliança.", "Pressa e evidência superficial podem produzir decisões frágeis; ainda assim, a palavra dada recebe peso moral.", ["O que os líderes deixaram de fazer?","Consultar o SENHOR","Examinar os pães","Conversar com Josué","Ouvir os gibeonitas","Josué 9:14 identifica diretamente a falha de discernimento."], ["Mesmo enganados, os líderes reconheceram o peso do","juramento",".","exército","tributo","mapa","A promessa comunitária não foi tratada como descartável."]),
    L("O dia prolongado", ["Josué 10",10,1,10,43], ["joshua-southern-campaign","Socorro aos aliados e vitória"], "Quando Gibeão é atacada, Israel honra a aliança e marcha para socorrê-la. A narrativa poética celebra a intervenção divina na campanha do sul.", "O foco teológico está na fidelidade de Deus e no compromisso assumido, não em transformar linguagem de batalha em método cristão.", ["Por que Israel marchou para ajudar Gibeão?","Porque havia firmado aliança","Porque Gibeão era israelita","Para recuperar a arca","Porque Saul ordenou","Josué responde ao pedido de aliados que ele havia jurado proteger."], ["Josué não abandonou os","aliados",".","egípcios","filisteus","levitas","A palavra empenhada orientou a ação."]),
    L("A campanha do norte", ["Josué 11",11,1,11,23], ["joshua-northern-campaign","Perseverança diante de oposição"], "Uma coalizão numerosa reúne carros e guerreiros. Josué recebe ordem para não temer, vence a campanha e a narrativa resume um processo prolongado.", "Textos de guerra exigem humildade interpretativa e não podem legitimar hostilidade étnica ou religiosa hoje.", ["Que vantagem militar a coalizão do norte possuía?","Muitos carros","A arca da aliança","Sacerdotes levitas","O cordão de Raabe","Josué 11 destaca cavalos e carros como força ameaçadora."], ["A narrativa diz que Josué fez guerra por muito","tempo",".","ouro","território","segredo","Josué 11:18 impede imaginar toda a conquista como evento instantâneo."]),
    L("Reis vencidos", ["Josué 12",12,1,12,24], ["joshua-kings-summary","Memória organizada da jornada"], "O capítulo lista reis vencidos a leste sob Moisés e a oeste sob Josué. A lista funciona como memória geográfica da passagem do deserto para a terra.", "Resumos ajudam a comunidade a perceber continuidade: a nova liderança participa da mesma missão iniciada antes dela.", ["Que dois períodos a lista de Josué 12 conecta?","Moisés e Josué","Abraão e Davi","Saul e Salomão","Elias e Eliseu","O capítulo distingue conquistas a leste com Moisés e a oeste com Josué."], ["A lista preserva a memória da","jornada",".","idolatria","monarquia","seca","Nomes e lugares registram etapas da história comunitária."])
  ]},
  { id: "joshua-u04", title: "Repartir a terra", subtitle: "Herança, limites e refúgio em Josué 13–21", chapters: [13,14,15,16,17,18,19,20,21], lessons: [
    L("Ainda resta muita terra", ["Josué 13",13,1,13,33], ["joshua-unfinished-land","Promessa e tarefa inacabada"], "Josué envelhece, mas ainda existe terra a possuir. O texto combina promessa, limites reais e distribuição responsável.", "Maturidade reconhece o que Deus já fez sem fingir que todo trabalho terminou.", ["O que Deus diz ao Josué idoso?","Ainda resta muita terra","A missão acabou totalmente","Volte ao Egito","Construa um templo","Josué 13:1 mantém diante do povo uma tarefa ainda incompleta."], ["Fé madura reconhece progresso e trabalho ainda","inacabado",".","proibido","secreto","irrelevante","A promessa não elimina participação responsável."]),
    L("Calebe pede Hebrom", ["Josué 14–15",14,1,15,63], ["joshua-caleb","Fidelidade perseverante"], "Calebe relembra sua confiança desde Cades e pede a região montanhosa de Hebrom. Sua perseverança atravessa décadas.", "Fidelidade não é passividade; Calebe sustenta esperança, memória e disposição para servir ao longo do tempo.", ["Que território Calebe pediu?","Hebrom","Jericó","Siló","Gibeão","Josué 14 registra seu pedido pela região montanhosa de Hebrom."], ["Calebe perseverou desde os dias de","Cades-Barneia",".","Babel","Ai","Siquém","Ele liga a herança à promessa recebida décadas antes."]),
    L("Sete tribos aguardam", ["Josué 16–19",16,1,19,51], ["joshua-allotments","Participação e distribuição comunitária"], "Enquanto algumas tribos recebem herança, sete ainda não haviam tomado posse. Representantes percorrem a terra, registram-na e a divisão acontece em Siló.", "Receber oportunidade exige iniciativa, organização e atenção à justiça entre grupos.", ["Quantas tribos ainda aguardavam herança em Josué 18?","Sete","Duas","Doze","Uma","Josué pergunta até quando as sete tribos demorariam a tomar posse."], ["Representantes deveriam descrever a terra por","escrito",".","sonhos","canções","rumores","O levantamento cria base para a distribuição."]),
    L("Refúgio e cidades levíticas", ["Josué 20–21",20,1,21,45], ["joshua-refuge","Justiça, refúgio e serviço"], "Cidades de refúgio protegem o homicida involuntário até julgamento; cidades levíticas são distribuídas entre as tribos. O bloco termina afirmando a fidelidade das promessas.", "Justiça bíblica inclui proteção contra vingança imediata, devido processo e provisão para quem serve sem território próprio.", ["Quem podia buscar uma cidade de refúgio?","Quem matasse sem intenção","Qualquer exército invasor","Somente reis","Apenas sacerdotes","Josué 20 liga refúgio a morte não intencional e julgamento."], ["Nenhuma das boas promessas de Deus","falhou",".","mudou de autor","foi escondida","dependia de Faraó","Josué 21:45 resume a fidelidade divina."])
  ]},
  { id: "joshua-u05", title: "Escolher a fidelidade", subtitle: "Unidade, despedida e renovação em Josué 22–24", chapters: [22,23,24], lessons: [
    L("O altar junto ao Jordão", ["Josué 22",22,1,22,34], ["joshua-altar-witness","Conflito resolvido por escuta"], "Um altar construído pelas tribos orientais é interpretado como rebelião. Antes da guerra, uma delegação pergunta e descobre que o altar era testemunho de pertencimento.", "A comunidade evita violência quando investiga motivos, escuta explicações e preserva a unidade sem abandonar convicções.", ["O que evitou a guerra entre as tribos?","Diálogo e investigação","Uma tempestade","A fuga das tribos","A intervenção do Egito","A delegação ouviu a explicação antes de agir."], ["O altar foi chamado de","testemunho",".","trono","sepulcro","fortaleza","Ele lembraria que as tribos de ambos os lados pertenciam ao SENHOR."]),
    L("Despedida de Josué", ["Josué 23",23,1,23,16], ["joshua-farewell","Perseverança depois das vitórias"], "Josué reúne líderes e recorda o que Deus fez. O desafio agora é apegar-se ao SENHOR, guardar a aliança e resistir à assimilação idolátrica.", "Começar bem não dispensa perseverança; vitórias passadas não substituem fidelidade presente.", ["A que Israel deveria se apegar?","Ao SENHOR","Aos carros de guerra","À riqueza de Jericó","Aos deuses das nações","Josué 23:8 chama o povo a permanecer unido ao SENHOR."], ["Memórias de vitória devem alimentar","fidelidade",".","orgulho","isolamento","violência","Josué transforma lembrança em chamado perseverante."]),
    L("Eu e minha casa", ["Josué 24:1–28",24,1,24,28], ["joshua-choose-service","Escolha e serviço da aliança"], "Em Siquém, Josué reconta a iniciativa de Deus desde Abraão. Depois chama o povo a abandonar outros deuses e escolher a quem servir.", "A escolha responde à graça já narrada; não é decisão sem contexto, mas compromisso público e concreto.", ["Onde Josué reuniu o povo para renovar a aliança?","Siquém","Jericó","Belém","Hebrom","Josué 24 situa a assembleia em Siquém."], ["Eu e minha casa serviremos ao","SENHOR",".","rei de Jericó","Egito","Jordão","A frase expressa compromisso de lealdade."]),
    L("O fim de uma geração", ["Josué 24:29–33",24,29,24,33], ["joshua-generation-transition","Legado e transição geracional"], "O livro termina com as mortes de Josué e Eleazar e o sepultamento dos ossos de José. A geração serve ao SENHOR enquanto preserva memória viva de suas obras.", "Legado depende de comunidades que contam, praticam e renovam a história da fé para além de um líder.", ["Que ossos foram sepultados em Siquém?","Os de José","Os de Moisés","Os de Arão","Os de Acã","Josué 24:32 liga o final do livro à promessa feita no Egito."], ["A história de José conecta o Êxodo à","terra prometida",".","monarquia","Babilônia","Galileia","O sepultamento conclui uma longa linha de esperança."])
  ]}
];

export const joshuaUnits = buildHistoricalUnits("joshua", "Josué", seeds);
