import { buildHistoricalUnits, type HistoricalLessonSeed, type HistoricalUnitSeed } from "../historical/buildHistoricalUnits";
const L=(title:string,reference:HistoricalLessonSeed["reference"],concept:[string,string],teaching:string,formation:string,question:HistoricalLessonSeed["question"],fill:HistoricalLessonSeed["fill"]):HistoricalLessonSeed=>({title,reference,concept,teaching,formation,question,fill});
const seeds:HistoricalUnitSeed[]=[
{id:"1-samuel-u01",title:"Samuel aprende a ouvir",subtitle:"O nascimento de Samuel e a crise sacerdotal em 1 Samuel 1–4",chapters:[1,2,3,4],lessons:[
L("A oração de Ana",["1 Samuel 1",1,1,1,28],["samuel-hannah","Oração honesta e entrega"],"Ana leva sua angústia a Deus, é julgada apressadamente por Eli e depois acolhida. Ao receber Samuel, cumpre o voto e o entrega ao serviço do SENHOR.","Oração bíblica pode incluir lágrimas e palavras silenciosas; receber uma dádiva também traz responsabilidade.",["Quem interpretou mal a oração de Ana?","Eli","Elcana","Samuel","Hofni","Eli pensou que Ana estivesse embriagada."],["Ana chamou o menino de","Samuel",".","Saul","Davi","Jônatas","O nome está ligado ao pedido feito ao SENHOR."]),
L("O cântico e as duas casas",["1 Samuel 2",2,1,2,36],["samuel-reversal","Deus reverte orgulho e humilhação"],"Ana canta sobre Deus que abate soberbos e levanta necessitados. O serviço de Samuel contrasta com a exploração dos filhos de Eli, que abusam do sacerdócio.","Posição religiosa não protege quem despreza pessoas e coisas santas; Deus ouve os vulneráveis.",["Com quem Ana diz que ninguém deve multiplicar palavras arrogantes?","Com Deus","Com Faraó","Com Samuel","Com Davi","Seu cântico anuncia que Deus pesa as ações."],["Samuel crescia diante do","SENHOR",".","rei","Egito","exército","O refrão contrasta sua formação com os filhos de Eli."]),
L("Fala, pois teu servo ouve",["1 Samuel 3",3,1,3,21],["samuel-call","Escuta e vocação profética"],"Samuel ouve seu nome e pensa que Eli o chama. Orientado pelo sacerdote, responde a Deus e recebe uma palavra difícil sobre a casa de Eli.","Discernir a voz de Deus envolve comunidade, disponibilidade e coragem para comunicar verdade sem prazer na condenação.",["Que resposta Eli ensinou a Samuel?","Fala, pois teu servo ouve","Dá-me um sinal no céu","Faz-me rei","Envia outro profeta","1 Samuel 3 registra a postura de escuta."],["Samuel foi reconhecido como","profeta",".","rei","guerreiro filisteu","sumo sacerdote","Deus confirmou sua palavra em Israel."]),
L("A arca não é amuleto",["1 Samuel 4",4,1,4,22],["samuel-ark-defeat","Presença divina não manipulável"],"Israel leva a arca à batalha como se garantisse vitória, mas é derrotado; Hofni e Fineias morrem e a arca é capturada.","Símbolos sagrados não substituem fidelidade nem permitem controlar Deus.",["Por que Israel levou a arca ao acampamento?","Esperava garantir vitória","Para coroar Samuel","Para escondê-la de Eli","Para atravessar o Jordão","O povo tratou a arca como garantia automática."],["A arca foi capturada pelos","filisteus",".","moabitas","egípcios","edomitas","A derrota confronta a tentativa de manipular a presença divina."])
]},
{id:"1-samuel-u02",title:"O Rei acima dos ídolos",subtitle:"A arca, Samuel e o pedido de um rei em 1 Samuel 5–8",chapters:[5,6,7,8],lessons:[
L("Dagom cai",["1 Samuel 5",5,1,5,12],["samuel-dagon","Soberania de Deus em território inimigo"],"A arca é colocada no templo de Dagom, mas o ídolo cai e as cidades filisteias sofrem. Deus não depende do exército derrotado para demonstrar sua soberania.","A derrota do povo não significa derrota de Deus; nenhum ídolo o incorpora ou aprisiona.",["Diante de que ídolo a arca foi colocada?","Dagom","Baal-Zebube","Moloque","Aserá","Dagom cai diante da arca em Asdode."],["O ídolo caiu com o rosto em","terra",".","água","fogo","uma mesa","A postura comunica humilhação diante do SENHOR."]),
L("A arca retorna",["1 Samuel 6",6,1,6,21],["samuel-ark-return","Reverência e retorno da arca"],"Após sete meses, os filisteus enviam a arca em um carro novo com oferta pela culpa. As vacas seguem diretamente a Bete-Semes, confirmando que a aflição não foi acaso.","Reverência reconhece que Deus não é objeto de curiosidade ou controle.",["Para onde as vacas levaram a arca?","Bete-Semes","Belém","Ramá","Gibeá","O trajeto confirma a direção divina."],["Os filisteus enviaram uma oferta pela","culpa",".","coroação","colheita","guerra","A oferta reconhecia responsabilidade."]),
L("Ebenézer",["1 Samuel 7",7,1,7,17],["samuel-ebenezer","Arrependimento e ajuda de Deus"],"Samuel chama Israel a remover ídolos e voltar de todo coração. Após a vitória, ergue uma pedra chamada Ebenézer: até aqui nos ajudou o SENHOR.","Memória fiel começa com arrependimento e celebra ajuda divina, não superioridade humana.",["O que significa Ebenézer no contexto?","Pedra de ajuda","Trono do rei","Casa da arca","Vale da guerra","Samuel marca a ajuda recebida de Deus."],["Israel deveria remover os deuses","estrangeiros",".","domésticos apenas","do Egito somente","de Samuel","A volta ao SENHOR exigia mudança de lealdade."]),
L("Dá-nos um rei",["1 Samuel 8",8,1,8,22],["samuel-demand-king","Desejo de ser como as nações"],"Os anciãos pedem um rei como as outras nações. Deus manda Samuel advertir que o rei tomará filhos, terras e recursos, mas o povo insiste.","Instituições podem servir ao bem, porém concentração de poder exige limites e discernimento.",["Qual motivo o povo apresenta para querer rei?","Ser como as outras nações","Construir a arca","Voltar ao Egito","Substituir os levitas","1 Samuel 8 repete o desejo de conformidade política."],["Samuel advertiu que o rei iria","tomar",".","libertar sempre","recusar impostos","abolir exércitos","O verbo repetido expõe o custo da monarquia."])
]},
{id:"1-samuel-u03",title:"Saul: chamado e ruptura",subtitle:"Ascensão, vitórias e desobediência em 1 Samuel 9–15",chapters:[9,10,11,12,13,14,15],lessons:[
L("Saul é encontrado",["1 Samuel 9–10",9,1,10,27],["samuel-saul-call","Chamado, unção e sinais"],"Buscando jumentas perdidas, Saul encontra Samuel e é ungido. Sinais confirmam o chamado, mas ele se esconde entre a bagagem quando apresentado.","Chamado pode encontrar alguém em tarefas comuns; insegurança, porém, precisa ser tratada para não governar a liderança.",["Onde Saul se escondeu na apresentação pública?","Entre a bagagem","No templo de Dagom","Em Belém","Na casa de Samuel","1 Samuel 10:22 registra sua ocultação."],["Samuel ungiu Saul com","óleo",".","água do Jordão","cinzas","sangue de cordeiro","A unção marca sua designação."]),
L("Vitória e renovação",["1 Samuel 11–12",11,1,12,25],["samuel-renewal","Vitória, prestação de contas e aliança"],"Saul reúne Israel e liberta Jabes-Gileade. Em Gilgal, o reino é renovado, e Samuel presta contas de sua liderança e relembra a fidelidade de Deus.","Celebração pública deve incluir memória, exame de integridade e renovação da responsabilidade.",["Que cidade Saul libertou dos amonitas?","Jabes-Gileade","Jericó","Belém","Siquém","A ameaça contra Jabes mobiliza Israel."],["Samuel perguntou se havia tomado o boi ou jumento de","alguém",".","Saul","Faraó","Davi","Ele oferece transparência sobre seu ministério."]),
L("Impaciência e voto imprudente",["1 Samuel 13–14",13,1,14,52],["samuel-saul-impatience","Medo, presunção e liderança"],"Saul oferece sacrifício sem esperar Samuel. Depois faz um juramento que impede os soldados de comer e quase custa a vida de Jônatas, cuja fé havia impulsionado a vitória.","Pressão não justifica ultrapassar limites; líderes inseguros podem impor pesos que enfraquecem a comunidade.",["Quem atacou a guarnição filisteia confiando que Deus podia salvar?","Jônatas","Eli","Jessé","Agague","Jônatas age com seu escudeiro."],["O juramento de Saul deixou o povo","exausto",".","rico","oculto","sem rei","A proibição de alimento prejudicou o exército."]),
L("Obedecer é melhor",["1 Samuel 15",15,1,15,35],["samuel-saul-rejection","Obediência versus aparência religiosa"],"Saul poupa Agague e o melhor dos animais, depois chama sua decisão de sacrifício. Samuel denuncia a racionalização e anuncia a rejeição de Saul como rei.","Práticas religiosas não compensam desobediência deliberada nem transferência de culpa.",["O que Samuel diz ser melhor que sacrificar?","Obedecer","Conquistar","Jejuar","Reinar","1 Samuel 15:22 contrasta escuta obediente e ritual usado como desculpa."],["Saul culpou o","povo",".","profeta Natã","Egito","Jônatas","Ele evita assumir plenamente sua decisão."])
]},
{id:"1-samuel-u04",title:"Davi surge",subtitle:"Unção, Golias, amizade e perseguição em 1 Samuel 16–20",chapters:[16,17,18,19,20],lessons:[
L("Deus vê o coração",["1 Samuel 16",16,1,16,23],["samuel-david-anointed","Critério divino e unção de Davi"],"Samuel procura aparência régia entre os filhos de Jessé, mas Deus escolhe Davi, o mais novo que cuidava das ovelhas. Ele é ungido no meio dos irmãos.","O texto não despreza o corpo; confronta julgamentos que reduzem pessoas à aparência e status.",["Onde Davi estava quando Samuel chegou?","Cuidando das ovelhas","No exército de Saul","No templo","Em Moabe","Jessé precisou mandar buscá-lo do campo."],["O ser humano vê a aparência, porém Deus vê o","coração",".","exército","ouro","trono","1 Samuel 16:7 corrige o critério de Samuel."]),
L("Davi e Golias",["1 Samuel 17",17,1,17,58],["samuel-goliath","Confiança no Deus vivo"],"Golias desafia Israel, e Davi recusa a armadura de Saul. Ele se apoia na experiência de cuidado do rebanho e na honra do Deus vivo.","Fé não é negar o tamanho do desafio, mas recusar que ele tenha a palavra final.",["Que arma Davi usou para derrubar Golias?","Uma funda","A espada de Saul","Uma lança","Um arco filisteu","Uma pedra lançada pela funda atinge Golias."],["Davi disse que a batalha pertence ao","SENHOR",".","rei Saul","mais forte","exército filisteu","Sua confiança desloca o centro da própria habilidade."]),
L("Jônatas e a inveja de Saul",["1 Samuel 18–19",18,1,19,24],["samuel-jealousy","Amizade fiel e inveja destrutiva"],"Jônatas faz aliança com Davi, enquanto Saul interpreta o sucesso do jovem como ameaça. A inveja produz tentativas de morte e divide a casa real.","Amizade celebra o dom do outro; inveja transforma pessoas em rivais e corrói julgamento.",["Quem fez aliança de amizade com Davi?","Jônatas","Agague","Eli","Nabal","Jônatas entrega símbolos de sua posição a Davi."],["A reação de Saul ao sucesso foi marcada por","inveja",".","gratidão","arrependimento","indiferença","O refrão das mulheres alimenta seu medo."]),
L("A despedida dos amigos",["1 Samuel 20",20,1,20,42],["samuel-covenant-friendship","Aliança, verdade e despedida"],"Jônatas testa a intenção de Saul e avisa Davi por meio das flechas. Os amigos renovam aliança, choram e se separam.","Lealdade pode exigir dizer a verdade contra interesses familiares e proteger quem sofre injustiça.",["Como Jônatas sinalizou perigo a Davi?","Pela posição das flechas","Por uma trombeta","Por uma fogueira","Por uma carta egípcia","O código combinado usa flechas além do rapaz."],["Davi e Jônatas renovaram uma","aliança",".","guerra","coroação","sentença","A amizade é formulada como compromisso diante de Deus."])
]},
{id:"1-samuel-u05",title:"Davi no deserto",subtitle:"Fuga, misericórdia e escolhas difíceis em 1 Samuel 21–26",chapters:[21,22,23,24,25,26],lessons:[
L("Pão e espada",["1 Samuel 21–22",21,1,22,23],["samuel-nob","Fuga, medo e consequências"],"Davi recebe pão consagrado e a espada de Golias em Nobe, depois finge loucura em Gate. Doeg denuncia os sacerdotes, e Saul ordena massacre; Abiatar escapa.","A narrativa não idealiza Davi e expõe como paranoia no poder ameaça inocentes e instituições inteiras.",["Quem escapou do massacre dos sacerdotes?","Abiatar","Doeg","Aimeleque","Saul","Abiatar foge e se une a Davi."],["Doeg era o","edomita",".","moabita","egípcio","gibeonita","Ele denuncia e executa a violência ordenada por Saul."]),
L("Consultar antes de agir",["1 Samuel 23",23,1,23,29],["samuel-keilah","Direção divina e prudência"],"Davi consulta a Deus antes de libertar Queila e novamente quando descobre que a cidade o entregaria a Saul. Jônatas o fortalece em Deus no deserto.","Coragem e prudência caminham juntas; pedir direção pode confirmar ação ou indicar retirada.",["Quem fortaleceu Davi em Deus?","Jônatas","Nabal","Doeg","Samuel","1 Samuel 23:16 descreve o encontro no deserto."],["Davi libertou a cidade de","Queila",".","Jericó","Samaria","Berseba","Ele enfrentou os filisteus após consultar Deus."]),
L("Davi poupa Saul",["1 Samuel 24",24,1,24,22],["samuel-spare-saul","Misericórdia e recusa da vingança"],"Na caverna, Davi corta a orla do manto de Saul, mas se recusa a matá-lo. Depois mostra a prova e apela ao julgamento de Deus.","Ter oportunidade e poder não torna a vingança correta; domínio próprio pode interromper a violência.",["O que Davi cortou de Saul?","A orla do manto","O cabelo","A lança","A sandália","A parte do manto prova proximidade sem homicídio."],["Davi recusou fazer justiça com as próprias","mãos",".","palavras","riquezas","tropas","Ele entrega o julgamento a Deus."]),
L("Abigail impede sangue",["1 Samuel 25–26",25,1,26,25],["samuel-abigail","Sabedoria pacificadora e nova misericórdia"],"Nabal despreza Davi, que reage com intenção de vingança. Abigail leva provisões, argumenta com sabedoria e impede derramamento de sangue. Depois Davi poupa Saul novamente.","Uma intervenção corajosa e sábia pode impedir que alguém transforme ofensa em pecado maior.",["Quem convenceu Davi a não atacar a casa de Nabal?","Abigail","Mical","Merabe","Ana","Abigail assume iniciativa e apela ao futuro de Davi."],["No acampamento, Davi tomou a lança e o jarro de","água",".","óleo","vinho","mel","Esses objetos provam que ele poderia ter ferido Saul."])
]},
{id:"1-samuel-u06",title:"O fim de Saul",subtitle:"Exílio, crise e transição em 1 Samuel 27–31",chapters:[27,28,29,30,31],lessons:[
L("Davi entre os filisteus",["1 Samuel 27",27,1,27,12],["samuel-ziklag","Sobrevivência e ambiguidade no exílio"],"Com medo de Saul, Davi vive entre os filisteus e recebe Ziclague. Ele usa engano para manter a confiança de Aquis enquanto realiza ataques.","A sobrevivência em ambiente hostil pode produzir escolhas moralmente ambíguas; o narrador não chama cada estratégia de modelo.",["Que cidade Aquis deu a Davi?","Ziclague","Belém","Siló","Ramá","Ziclague se torna base de Davi."],["Davi buscou refúgio entre os","filisteus",".","amonitas","egípcios","midianitas","Ele acreditou que Saul cessaria a perseguição."]),
L("Saul e a médium",["1 Samuel 28",28,1,28,25],["samuel-endor","Desespero e busca proibida"],"Sem resposta e tomado de medo, Saul procura uma médium em En-Dor, prática que ele próprio havia proibido. A mensagem confirma o juízo já anunciado.","Desespero não transforma meios proibidos em fontes seguras de direção; anos de resistência culminam em silêncio aterrador.",["Onde vivia a médium procurada por Saul?","En-Dor","Belém","Hebrom","Jericó","1 Samuel 28 localiza o encontro em En-Dor."],["Saul procurou a médium porque estava dominado pelo","medo",".","júbilo","sono","orgulho de vitória","O exército filisteu o apavorou."]),
L("Rejeitado e restaurado",["1 Samuel 29–30",29,1,30,31],["samuel-ziklag-recovery","Crise, fortalecimento e partilha"],"Chefes filisteus rejeitam Davi; ao voltar, ele encontra Ziclague queimada. Fortalece-se no SENHOR, recupera famílias e bens e determina partilha também com quem ficou junto à bagagem.","A comunidade honra funções diferentes e recusa medir dignidade apenas pela linha de frente.",["Em quem Davi se fortaleceu durante a crise?","No SENHOR","Em Aquis","Em Saul","Nos amalequitas","1 Samuel 30:6 marca a virada do desespero."],["Os que ficaram com a bagagem também receberam","parte",".","castigo","exílio","silêncio","Davi estabelece partilha entre combatentes e apoio."]),
L("Saul morre em Gilboa",["1 Samuel 31",31,1,31,13],["samuel-saul-death","Queda trágica e honra aos mortos"],"Israel é derrotado no monte Gilboa; Saul e seus filhos morrem. Homens de Jabes-Gileade recuperam os corpos, lembrando o primeiro ato libertador de Saul.","O livro termina em luto, não em celebração do rival. Uma vida pode conter chamado real, escolhas destrutivas e memória complexa.",["Quem recuperou os corpos de Saul e seus filhos?","Homens de Jabes-Gileade","Soldados egípcios","Sacerdotes de Nobe","Gibeonitas","Jabes honra o rei que antes libertara sua cidade."],["A última batalha ocorreu no monte","Gilboa",".","Carmelo","Sinai","Tabor","1 Samuel 31 situa ali a derrota."])
]}
];
export const firstSamuelUnits=buildHistoricalUnits("1-samuel","1 Samuel",seeds);
